/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class FormKrs extends javax.swing.JFrame {
    Connection conn;

private void koneksi() {
    try {
        conn = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/krs",
                "root",
                ""
        );
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
                "Koneksi gagal : " + e.getMessage());
    }
}
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormKrs.class.getName());

    /**
     * Creates new form FormKrs
     */
    public FormKrs() {
        initComponents();
        
        koneksi();
    tampilMatkul();
    loadMahasiswa();

    buatCheckbox();
    }

   private void tampilMatkul() {

    DefaultTableModel model =
            new DefaultTableModel() {

        @Override
        public Class<?> getColumnClass(int column) {

            if(column == 0){
                return Boolean.class;
            }

            return Object.class;
        }

        @Override
        public boolean isCellEditable(
                int row,
                int column) {

            return column == 0;
        }
    };

    model.addColumn("Pilih");
    model.addColumn("ID Kelas");
    model.addColumn("Kode MK");
    model.addColumn("Mata Kuliah");
    model.addColumn("SKS");

    try {

        String sql =
        "SELECT kelas.id_kelas, " +
        "mata_kuliah.kode_mk, " +
        "mata_kuliah.nama_mk, " +
        "mata_kuliah.sks " +
        "FROM kelas " +
        "JOIN mata_kuliah " +
        "ON kelas.kode_mk = mata_kuliah.kode_mk";

        PreparedStatement ps =
                conn.prepareStatement(sql);

        ResultSet rs = ps.executeQuery();

        while (rs.next()) {

            model.addRow(new Object[]{
                false,
                rs.getInt("id_kelas"),
                rs.getString("kode_mk"),
                rs.getString("nama_mk"),
                rs.getInt("sks")
            });
        }

        jTable1.setModel(model);

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
                e.getMessage());
    }
}
    
    private void loadMahasiswa() {

    try {

        String nim = "2022001002";

        String sql =
        "SELECT m.nama, p.nama_prodi " +
        "FROM mahasiswa m " +
        "JOIN prodi p " +
        "ON m.id_prodi = p.id_prodi " +
        "WHERE m.nim=?";

        PreparedStatement ps =
                conn.prepareStatement(sql);

        ps.setString(1, nim);

        ResultSet rs = ps.executeQuery();

        if(rs.next()) {

            Nim.setText(nim);
            Nama.setText(rs.getString("nama"));
            Prodi.setText(
                    rs.getString("nama_prodi"));

            Semester.setText("3");
            TahunAjaran.setText("2026/2027");
            MaksimalSKS.setText("24");
            StatusKrs.setText("Menunggu");
            TotalSksDipilih.setText("0");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
                e.getMessage());
    }
}
    
    private void buatCheckbox() {

    jTable1.getModel()
            .addTableModelListener(e -> {

        int total = 0;

        for (int i = 0;
                i < jTable1.getRowCount();
                i++) {

            Boolean pilih =
            (Boolean) jTable1
            .getValueAt(i, 0);

            if (pilih != null && pilih) {

                total += Integer.parseInt(
                        jTable1.getValueAt(i,4)
                                .toString()
                );
            }
        }

        TotalSksDipilih
                .setText(String.valueOf(total));
    });
}
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Nim = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        Nama = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        Prodi = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        Semester = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        TahunAjaran = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        MaksimalSKS = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        TotalSksDipilih = new javax.swing.JTextPane();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        StatusKrs = new javax.swing.JTextPane();
        Simpan = new javax.swing.JButton();
        Cetak = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        back = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nim ");

        jLabel2.setText("Nama");

        jLabel3.setText("Prodi");

        jLabel4.setText("Semester");

        jLabel5.setText("Tahun Ajaran");

        jLabel6.setText("Maksimal SKS");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Pilihan", "kode mk", "Mata kuliah ", "SKS", "Jadwal"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel7.setText("Daftar MataKuliah");

        jLabel8.setText("Total Sks Dipilih");

        jScrollPane4.setViewportView(Nim);

        jScrollPane5.setViewportView(Nama);

        jScrollPane6.setViewportView(Prodi);

        jScrollPane7.setViewportView(Semester);

        jScrollPane8.setViewportView(TahunAjaran);

        jScrollPane9.setViewportView(MaksimalSKS);

        jScrollPane2.setViewportView(TotalSksDipilih);

        jLabel10.setText("Status Krs");

        jScrollPane10.setViewportView(StatusKrs);

        Simpan.setText("Simpan");
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });

        Cetak.setText("Cetak");
        Cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CetakActionPerformed(evt);
            }
        });

        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        back.setText("back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                        .addComponent(jScrollPane5)
                        .addComponent(jScrollPane6)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(Simpan)
                        .addGap(31, 31, 31)
                        .addComponent(Cetak)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(back)
                            .addComponent(Reset)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Simpan)
                    .addComponent(Cetak)
                    .addComponent(Reset))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
          new FormAdmin().setVisible(true);
    this.dispose();

    }//GEN-LAST:event_backActionPerformed

    private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
        // TODO add your handling code here:
        try {

        if (TotalSksDipilih.getText().equals("0")) {
            JOptionPane.showMessageDialog(this,
                    "Pilih mata kuliah terlebih dahulu!");
            return;
        }

        String sqlKrs =
                "INSERT INTO krs " +
                "(nim, semester, tahun_ajaran, status) " +
                "VALUES (?, ?, ?, ?)";

        PreparedStatement ps =
                conn.prepareStatement(
                        sqlKrs,
                        PreparedStatement.RETURN_GENERATED_KEYS
                );

        ps.setString(1, Nim.getText());
        ps.setInt(2,
                Integer.parseInt(
                        Semester.getText()));

        ps.setString(3,
                TahunAjaran.getText());

        ps.setString(4,
                "Menunggu");

        ps.executeUpdate();

        ResultSet rs = ps.getGeneratedKeys();

        int idKrs = 0;

        if (rs.next()) {
            idKrs = rs.getInt(1);
        }

        // simpan detail krs
        for (int i = 0;
                i < jTable1.getRowCount();
                i++) {

            Boolean pilih =
                    (Boolean) jTable1
                            .getValueAt(i, 0);

            if (pilih != null && pilih) {

                int idKelas =
                        Integer.parseInt(
                                jTable1
                                        .getValueAt(i, 1)
                                        .toString());

                String sqlDetail =
                        "INSERT INTO krs_detail " +
                        "(id_krs, id_kelas) " +
                        "VALUES (?, ?)";

                PreparedStatement ps2 =
                        conn.prepareStatement(
                                sqlDetail);

                ps2.setInt(1, idKrs);
                ps2.setInt(2, idKelas);

                ps2.executeUpdate();
            }
        }

        JOptionPane.showMessageDialog(this,
                "KRS berhasil disimpan!");

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
                "Gagal simpan : "
                + e.getMessage());
    }
    }//GEN-LAST:event_SimpanActionPerformed

    private void CetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CetakActionPerformed
        // TODO add your handling code here:
         StringBuilder hasil = new StringBuilder();

    hasil.append("===== KARTU RENCANA STUDI =====\n\n");
    hasil.append("NIM : ").append(Nim.getText()).append("\n");
    hasil.append("Nama : ").append(Nama.getText()).append("\n");
    hasil.append("Prodi : ").append(Prodi.getText()).append("\n");
    hasil.append("Semester : ").append(Semester.getText()).append("\n");
    hasil.append("Tahun Ajaran : ").append(TahunAjaran.getText()).append("\n\n");

    hasil.append("Mata Kuliah Dipilih:\n");

    for (int i = 0; i < jTable1.getRowCount(); i++) {

        Boolean pilih =
                (Boolean) jTable1.getValueAt(i, 0);

        if (pilih != null && pilih) {

            hasil.append("- ")
                  .append(jTable1.getValueAt(i, 3))
                  .append(" (")
                  .append(jTable1.getValueAt(i, 2))
                  .append(") - ")
                  .append(jTable1.getValueAt(i, 4))
                  .append(" SKS\n");
        }
    }

    hasil.append("\nTotal SKS : ")
          .append(TotalSksDipilih.getText());

    JOptionPane.showMessageDialog(
            this,
            hasil.toString(),
            "Cetak KRS",
            JOptionPane.INFORMATION_MESSAGE
    );
    }//GEN-LAST:event_CetakActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < jTable1.getRowCount(); i++) {
        jTable1.setValueAt(false, i, 0);
    }

    // reset total sks
    TotalSksDipilih.setText("0");

    // reset status
    StatusKrs.setText("0");

    JOptionPane.showMessageDialog(this,
            "Data berhasil direset");

    }//GEN-LAST:event_ResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormKrs().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cetak;
    private javax.swing.JTextPane MaksimalSKS;
    private javax.swing.JTextPane Nama;
    private javax.swing.JTextPane Nim;
    private javax.swing.JTextPane Prodi;
    private javax.swing.JButton Reset;
    private javax.swing.JTextPane Semester;
    private javax.swing.JButton Simpan;
    private javax.swing.JTextPane StatusKrs;
    private javax.swing.JTextPane TahunAjaran;
    private javax.swing.JTextPane TotalSksDipilih;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
