/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author user
 */
public class FormJadwal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormJadwal.class.getName());

    /**
     * Creates new form FormJadwal
     */
      // menyimpan id jadwal yang dipilih
    private String idJadwal = "";

    public FormJadwal() {
        initComponents();

        tampilDataJadwal();
    }

    // ===================== TAMPIL DATA =====================
    private void tampilDataJadwal() {

        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("ID");
        model.addColumn("Hari");
        model.addColumn("Jam");
        model.addColumn("Ruangan");

        try {

            String sql = "SELECT * FROM jadwal";

            Connection conn = new database().koneksi();

            Statement st = conn.createStatement();

            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {

                String jam =
                        rs.getString("jam_mulai")
                        + "-"
                        + rs.getString("jam_selesai");

                model.addRow(new Object[]{
                    rs.getString("id_jadwal"),
                    rs.getString("hari"),
                    jam,
                    rs.getString("ruang")
                });
            }

            jTable1.setModel(model);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    null,
                    "Gagal tampil data : " + e.getMessage());
        }
    }

    // ===================== RESET FORM =====================
    private void resetForm() {

        Hari.setSelectedIndex(0);
        Ruangan.setSelectedIndex(0);
        Jammulai.setSelectedIndex(0);

        idJadwal = "";
    }

    // ===================== PILIH DATA =====================
    private void pilihDataTabel() {

        int baris = jTable1.getSelectedRow();

        if (baris != -1) {

            idJadwal =
                    jTable1.getValueAt(baris, 0).toString();

            Hari.setSelectedItem(
                    jTable1.getValueAt(baris, 1).toString());

            Jammulai.setSelectedItem(
                    jTable1.getValueAt(baris, 2).toString());

            Ruangan.setSelectedItem(
                    jTable1.getValueAt(baris, 3).toString());
        }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Hari = new javax.swing.JComboBox<>();
        Ruangan = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Jammulaiselesai = new javax.swing.JLabel();
        Jammulai = new javax.swing.JComboBox<>();
        simpan = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Jadwal");

        jLabel3.setText("Hari");

        jLabel6.setText(" Ruangan ");

        Hari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Senin", "selasa", "Rabu", "kamis", "jumat", "sabtu" }));
        Hari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HariActionPerformed(evt);
            }
        });

        Ruangan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1.03", "2.04" }));
        Ruangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RuanganActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mk", "Hari", "Jam ", "Ruangan"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        Jammulaiselesai.setText("Jam Mulai-selesai");

        Jammulai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "07:00-08:40", "08:40-10:20", "10:20-12:00", "13:00-14:40", "15:00-16:40", "17:00-18:40" }));
        Jammulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JammulaiActionPerformed(evt);
            }
        });

        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        edit.setText("edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        hapus.setText("hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        back.setText("back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Ruangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Hari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jammulaiselesai)
                            .addComponent(simpan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edit)
                            .addComponent(Jammulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(hapus))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(back)
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Hari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Ruangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jammulaiselesai)
                    .addComponent(Jammulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpan)
                    .addComponent(edit)
                    .addComponent(hapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void RuanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RuanganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RuanganActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
         try {

        String jam =
                Jammulai.getSelectedItem().toString();

        String[] splitJam =
                jam.split("-");

        String sql =
                "INSERT INTO jadwal "
                + "(id_kelas,hari,"
                + "jam_mulai,"
                + "jam_selesai,"
                + "ruang) "
                + "VALUES (?,?,?,?,?)";

        Connection conn =
                new database().koneksi();

        PreparedStatement pst =
                conn.prepareStatement(sql);

        pst.setInt(1, 1);

        pst.setString(
                2,
                Hari.getSelectedItem().toString());

        pst.setString(
                3,
                splitJam[0]);

        pst.setString(
                4,
                splitJam[1]);

        pst.setString(
                5,
                Ruangan.getSelectedItem().toString());

        pst.executeUpdate();

        JOptionPane.showMessageDialog(
                null,
                "Data berhasil disimpan");

        tampilDataJadwal();
        resetForm();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                null,
                "Gagal simpan : "
                + e.getMessage());
    }
    }//GEN-LAST:event_simpanActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        try {

        if (idJadwal.equals("")) {

            JOptionPane.showMessageDialog(
                    null,
                    "Pilih data dulu");

            return;
        }

        String jam =
                Jammulai.getSelectedItem()
                        .toString();

        String[] splitJam =
                jam.split("-");

        String sql =
                "UPDATE jadwal SET "
                + "hari=?, "
                + "jam_mulai=?, "
                + "jam_selesai=?, "
                + "ruang=? "
                + "WHERE id_jadwal=?";

        Connection conn =
                new database().koneksi();

        PreparedStatement pst =
                conn.prepareStatement(sql);

        pst.setString(
                1,
                Hari.getSelectedItem().toString());

        pst.setString(
                2,
                splitJam[0]);

        pst.setString(
                3,
                splitJam[1]);

        pst.setString(
                4,
                Ruangan.getSelectedItem().toString());

        pst.setString(
                5,
                idJadwal);

        pst.executeUpdate();

        JOptionPane.showMessageDialog(
                null,
                "Data berhasil diedit");

        tampilDataJadwal();
        resetForm();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                null,
                "Gagal edit : "
                + e.getMessage());
    }
    }//GEN-LAST:event_editActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
          try {

        if (idJadwal.equals("")) {

            JOptionPane.showMessageDialog(
                    null,
                    "Pilih data dulu");

            return;
        }

        String sql =
                "DELETE FROM jadwal "
                + "WHERE id_jadwal=?";

        Connection conn =
                new database().koneksi();

        PreparedStatement pst =
                conn.prepareStatement(sql);

        pst.setString(1, idJadwal);

        pst.executeUpdate();

        JOptionPane.showMessageDialog(
                null,
                "Data berhasil dihapus");

        tampilDataJadwal();
        resetForm();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                null,
                "Gagal hapus : "
                + e.getMessage());
    }
    }//GEN-LAST:event_hapusActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        new FormAdmin().setVisible(true);
    dispose();
    }//GEN-LAST:event_backActionPerformed

    private void HariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HariActionPerformed

    private void JammulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JammulaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JammulaiActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        pilihDataTabel();
    }//GEN-LAST:event_jTable1MouseClicked

  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormJadwal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Hari;
    private javax.swing.JComboBox<String> Jammulai;
    private javax.swing.JLabel Jammulaiselesai;
    private javax.swing.JComboBox<String> Ruangan;
    private javax.swing.JButton back;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton simpan;
    // End of variables declaration//GEN-END:variables
}