/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author user
 */

public class FormKelas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormKelas.class.getName());
private String idKelas = "";
    /**
     * Creates new form FormKelas
     */
// ================= TAMPIL DATA =================
private void tampilDataKelas() {

    DefaultTableModel model = new DefaultTableModel();

    model.addColumn("ID");
    model.addColumn("Kode MK");
    model.addColumn("Semester");
    model.addColumn("Tahun Ajaran");
    model.addColumn("Kapasitas");
    model.addColumn("ID Dosen");

    try {

        String sql = "SELECT * FROM kelas";

        Connection conn = new database().koneksi();
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(sql);

        while (rs.next()) {

            model.addRow(new Object[]{
                rs.getString("id_kelas"),
                rs.getString("kode_mk"),
                rs.getString("semester"),
                rs.getString("tahun_ajaran"),
                rs.getString("kapasitas"),
                rs.getString("id_dosen")
            });
        }

        TableKelas.setModel(model);

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                null,
                "Gagal tampil data : " + e.getMessage());
    }
}

// ================= RESET FORM =================
private void resetForm() {

    MataKuliah.setSelectedIndex(0);
    Smester.setSelectedIndex(0);
    Tahunajaran.setSelectedIndex(0);
    kapasitas1.setSelectedIndex(0);
    dosen.setSelectedIndex(0);

    idKelas = "";
}

// ================= PILIH DATA =================
private void pilihDataTabel() {

    int baris =
            TableKelas.getSelectedRow();

    if (baris != -1) {

        idKelas =
                TableKelas.getValueAt(
                        baris, 0).toString();

        MataKuliah.setSelectedItem(
                TableKelas.getValueAt(
                        baris, 1).toString());

        Smester.setSelectedItem(
                TableKelas.getValueAt(
                        baris, 2).toString());

        Tahunajaran.setSelectedItem(
                TableKelas.getValueAt(
                        baris, 3).toString());

        kapasitas1.setSelectedItem(
                TableKelas.getValueAt(
                        baris, 4).toString());

        dosen.setSelectedItem(
                TableKelas.getValueAt(
                        baris, 5).toString());
    }
}
    public FormKelas() {
        initComponents();
        dosen.setModel(
        new javax.swing.DefaultComboBoxModel<>(
            new String[] { "1", "2", "3" }
        )
    );
        tampilDataKelas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        KodeMk = new javax.swing.JLabel();
        Semester = new javax.swing.JLabel();
        TahunAjaran = new javax.swing.JLabel();
        Kapasitas = new javax.swing.JLabel();
        Dosen = new javax.swing.JLabel();
        MataKuliah = new javax.swing.JComboBox<>();
        Smester = new javax.swing.JComboBox<>();
        Tahunajaran = new javax.swing.JComboBox<>();
        kapasitas1 = new javax.swing.JComboBox<>();
        dosen = new javax.swing.JComboBox<>();
        simpan = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableKelas = new javax.swing.JTable();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Data Kelas");

        KodeMk.setText("Mata Kuliah");

        Semester.setText("Semester");

        TahunAjaran.setText("Tahun Ajaran");

        Kapasitas.setText("Kapasitas");

        Dosen.setText("Dosen");

        MataKuliah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TI102", "SI101", "SI102" }));
        MataKuliah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MataKuliahActionPerformed(evt);
            }
        });

        Smester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        Tahunajaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2025/2026", "2024/2025", "2023/2024", "2022/2023" }));

        kapasitas1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "35", "20", "15" }));

        dosen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "aryo", "erick", "tifa" }));
        dosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosenActionPerformed(evt);
            }
        });

        simpan.setText("simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        edit.setText("edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        hapus.setText("hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        TableKelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Mata Kuliah", "Kuota", "Dosen"
            }
        ));
        TableKelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableKelasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableKelas);

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Semester, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(KodeMk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(TahunAjaran)
                            .addComponent(Kapasitas)
                            .addComponent(Dosen, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MataKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Smester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Tahunajaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kapasitas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(back)
                                    .addComponent(hapus)
                                    .addComponent(edit)
                                    .addComponent(simpan)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KodeMk)
                    .addComponent(MataKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simpan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Semester)
                    .addComponent(Smester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TahunAjaran)
                    .addComponent(Tahunajaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hapus))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Kapasitas)
                    .addComponent(kapasitas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dosen)
                    .addComponent(dosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        try {

        String sql =
    "INSERT INTO kelas "
    + "(kode_mk, semester, tahun_ajaran, kapasitas, id_dosen) "
    + "VALUES (?,?,?,?,?)";

        Connection conn =
                new database().koneksi();

        PreparedStatement pst =
                conn.prepareStatement(sql);

        pst.setString(
                1,
                MataKuliah.getSelectedItem().toString());

        pst.setString(
                2,
                Smester.getSelectedItem().toString());

        pst.setString(
                3,
                Tahunajaran.getSelectedItem().toString());

        pst.setString(
                4,
                kapasitas1.getSelectedItem().toString());

        pst.setString(
                5,
                dosen.getSelectedItem().toString());

        pst.executeUpdate();

        JOptionPane.showMessageDialog(
                null,
                "Data berhasil disimpan");

        tampilDataKelas();
        resetForm();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                null,
                "Gagal simpan : "
                + e.getMessage());
    }
    }//GEN-LAST:event_simpanActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        try {

        if (idKelas.equals("")) {

            JOptionPane.showMessageDialog(
                    null,
                    "Pilih data dulu");

            return;
        }

        String sql =
    "UPDATE kelas SET "
    + "kode_mk=?, "
    + "semester=?, "
    + "tahun_ajaran=?, "
    + "kapasitas=?, "
    + "id_dosen=? "
    + "WHERE id_kelas=?";

        Connection conn =
                new database().koneksi();

        PreparedStatement pst =
                conn.prepareStatement(sql);

        pst.setString(
                1,
                MataKuliah.getSelectedItem().toString());

        pst.setString(
                2,
                Smester.getSelectedItem().toString());

        pst.setString(
                3,
                Tahunajaran.getSelectedItem().toString());

        pst.setString(
                4,
                kapasitas1.getSelectedItem().toString());

        pst.setString(
                5,
                dosen.getSelectedItem().toString());

        pst.setString(
                6,
                idKelas);

        pst.executeUpdate();

        JOptionPane.showMessageDialog(
                null,
                "Data berhasil di edit");

        tampilDataKelas();
        resetForm();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                null,
                "Gagal edit : "
                + e.getMessage());
    }
    }//GEN-LAST:event_editActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
         new FormAdmin().setVisible(true);
    dispose();
    }//GEN-LAST:event_backActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        try {

        if (idKelas.equals("")) {

            JOptionPane.showMessageDialog(
                    null,
                    "Pilih data dulu");

            return;
        }

        String sql =
                "DELETE FROM kelas "
                + "WHERE id_kelas=?";

        Connection conn =
                new database().koneksi();

        PreparedStatement pst =
                conn.prepareStatement(sql);

        pst.setString(1, idKelas);

        pst.executeUpdate();

        JOptionPane.showMessageDialog(
                null,
                "Data berhasil dihapus");

        tampilDataKelas();
        resetForm();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                null,
                "Gagal hapus : "
                + e.getMessage());
    }
    }//GEN-LAST:event_hapusActionPerformed

    private void TableKelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableKelasMouseClicked
        // TODO add your handling code here:
         pilihDataTabel();
    }//GEN-LAST:event_TableKelasMouseClicked

    private void dosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosenActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_dosenActionPerformed

    private void MataKuliahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MataKuliahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MataKuliahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormKelas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dosen;
    private javax.swing.JLabel Kapasitas;
    private javax.swing.JLabel KodeMk;
    private javax.swing.JComboBox<String> MataKuliah;
    private javax.swing.JLabel Semester;
    private javax.swing.JComboBox<String> Smester;
    private javax.swing.JTable TableKelas;
    private javax.swing.JLabel TahunAjaran;
    private javax.swing.JComboBox<String> Tahunajaran;
    private javax.swing.JButton back;
    private javax.swing.JComboBox<String> dosen;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> kapasitas1;
    private javax.swing.JButton simpan;
    // End of variables declaration//GEN-END:variables
}
