/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1.Mahasiswa;
import com.mycompany.mavenproject1.FormLogin;




/**
 *
 * @author user
 */
public class Dahboard extends javax.swing.JFrame {
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dahboard.class.getName());

    /**
     * Creates new form Dahboard
     */
    
    
    private String nim;
    private String nama;
    private String semester;
    private String prodi;

    public Dahboard() {
        initComponents();
    }

    public Dahboard(String nim,
                String nama,
                String semester,
                String prodi) {

    initComponents();

    this.nim = nim;
    this.nama = nama;
    this.semester = semester;
    this.prodi = prodi;

    jLabel1.setText("Selamat Datang, " + nama);

    System.out.println("NIM: " + nim);
    System.out.println("Nama: " + nama);
    System.out.println("Semester: " + semester);
    System.out.println("Prodi: " + prodi);

    jLabel1.setText("Selamat Datang, " + nama);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        IsiKRS = new javax.swing.JButton();
        HasilKRS = new javax.swing.JButton();
        JadwalKuliah = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        Profilmahasiswa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Dashboard Mahasiswa");

        IsiKRS.setText("Isi KRS");
        IsiKRS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IsiKRSActionPerformed(evt);
            }
        });

        HasilKRS.setText("Hasil KRS");
        HasilKRS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HasilKRSActionPerformed(evt);
            }
        });

        JadwalKuliah.setText("Jadwal Kuliah");
        JadwalKuliah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JadwalKuliahActionPerformed(evt);
            }
        });

        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        Profilmahasiswa.setText("Profil");
        Profilmahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfilmahasiswaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IsiKRS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HasilKRS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JadwalKuliah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Profilmahasiswa))
                    .addComponent(Logout))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IsiKRS)
                            .addComponent(HasilKRS)
                            .addComponent(JadwalKuliah)
                            .addComponent(Profilmahasiswa))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Logout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IsiKRSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IsiKRSActionPerformed
        // TODO add your handling code here:
        new IsiKrs(
        nim,
        nama,
        semester,
        prodi
).setVisible(true);

this.dispose();
    }//GEN-LAST:event_IsiKRSActionPerformed

    private void HasilKRSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HasilKRSActionPerformed
        // TODO add your handling code here:
        new HasilKRS(nim)
                .setVisible(true);
        dispose();
    }//GEN-LAST:event_HasilKRSActionPerformed

    private void JadwalKuliahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JadwalKuliahActionPerformed
        // TODO add your handling code here:
        new JadwalKuliah(
    nim,
    nama,
    semester,
    prodi
).setVisible(true);

dispose();  
    }//GEN-LAST:event_JadwalKuliahActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
         new FormLogin().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    private void ProfilmahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfilmahasiswaActionPerformed
        // TODO add your handling code here:
        new ProfilMahasiswa(
        nim,
        nama,
        semester,
        prodi
).setVisible(true);

dispose();
    }//GEN-LAST:event_ProfilmahasiswaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dahboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HasilKRS;
    private javax.swing.JButton IsiKRS;
    private javax.swing.JButton JadwalKuliah;
    private javax.swing.JButton Logout;
    private javax.swing.JButton Profilmahasiswa;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
