/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1.Mahasiswa;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.mycompany.mavenproject1.Koneksi;
/**
 *
 * @author user
 */
public class HasilKRS extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HasilKRS.class.getName());

    /**
     * Creates new form HasilKRS
     */
    private String nim;
    public HasilKRS(String nim) {
    initComponents();
    this.nim = nim;

    tampilData();
    tampilRiwayat();
}
    
    private void tampilData() {

    DefaultTableModel model =
            new DefaultTableModel();

    model.addColumn("Kode MK");
    model.addColumn("Mata Kuliah");
    model.addColumn("SKS");
    model.addColumn("Status");
    model.addColumn("Catatan");

    jTable2hasilkrs.setModel(model);

    try {

        Connection conn =
                Koneksi.getConnection();

        String sql =
        "SELECT mk.kode_mk, " +
        "mk.nama_mk, " +
        "mk.sks, " +
        "k.status, " +
        "COALESCE(k.catatan,'-') AS catatan " +
        "FROM krs k " +
        "JOIN krs_detail kd " +
        "ON k.id_krs = kd.id_krs " +
        "JOIN kelas kl " +
        "ON kd.id_kelas = kl.id_kelas " +
        "JOIN mata_kuliah mk " +
        "ON kl.kode_mk = mk.kode_mk " +
        "WHERE k.nim = ? " +
        "ORDER BY k.id_krs DESC";

        PreparedStatement ps =
                conn.prepareStatement(sql);

        ps.setString(1, nim);

        ResultSet rs =
                ps.executeQuery();

        int totalSKS = 0;
        boolean adaData = false;

        while(rs.next()) {

            adaData = true;

            int sks =
            rs.getInt("sks");

            totalSKS += sks;

            model.addRow(new Object[]{
                rs.getString("kode_mk"),
                rs.getString("nama_mk"),
                sks,
                rs.getString("status"),
                rs.getString("catatan")
            });
        }

        jLabel2.setText(
            "Informasi | Total SKS: "
            + totalSKS
        );

        if (!adaData) {

            JOptionPane.showMessageDialog(
                null,
                "Belum ada data KRS"
            );
        }

    } catch(Exception e) {

        JOptionPane.showMessageDialog(
                null,
                e.getMessage()
        );
    }
}
    
    private void tampilRiwayat() {

    DefaultTableModel model =
            new DefaultTableModel();

    model.addColumn("ID KRS");
    model.addColumn("Semester");
    model.addColumn("Tahun Ajaran");
    model.addColumn("Status");
    model.addColumn("Catatan");

    jTable2RiwayatKRS.setModel(model);

    try {

        Connection conn =
                Koneksi.getConnection();

        String sql =
                "SELECT id_krs, semester, tahun_ajaran, status, " +
                "COALESCE(catatan,'-') AS catatan " +
                "FROM krs " +
                "WHERE nim=? " +
                "ORDER BY id_krs DESC";

        PreparedStatement ps =
                conn.prepareStatement(sql);

        ps.setString(1, nim);

        ResultSet rs =
                ps.executeQuery();

        while(rs.next()) {

            model.addRow(new Object[]{
                rs.getInt("id_krs"),
                rs.getInt("semester"),
                rs.getString("tahun_ajaran"),
                rs.getString("status"),
                rs.getString("catatan")
            });
        }

    } catch(Exception e) {

        JOptionPane.showMessageDialog(
                this,
                e.getMessage()
        );
    }
}
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        Cetak = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2hasilkrs = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2RiwayatKRS = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Riwayat KRS");

        jLabel2.setText("Informasi");

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Cetak.setText("Cetak");
        Cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CetakActionPerformed(evt);
            }
        });

        jTable2hasilkrs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2hasilkrs);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("HASIL KRS");

        jTable2RiwayatKRS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable2RiwayatKRS);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(Cetak)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Back))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back)
                    .addComponent(Cetak))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        try {

        Connection conn =
                Koneksi.getConnection();

        String sql =
        "SELECT m.nama, " +
        "m.semester, " +
        "p.nama_prodi " +
        "FROM mahasiswa m " +
        "LEFT JOIN prodi p " +
        "ON m.id_prodi = p.id_prodi " +
        "WHERE m.nim=?";

        PreparedStatement ps =
                conn.prepareStatement(sql);

        ps.setString(1, nim);

        ResultSet rs =
                ps.executeQuery();

        if(rs.next()) {

            String nama =
                    rs.getString("nama");

            String semester =
                    rs.getString("semester");

            String prodi =
                    rs.getString("nama_prodi");

            new Dahboard(
                    nim,
                    nama,
                    semester,
                    prodi
            ).setVisible(true);

            dispose();
        }

    } catch(Exception e) {

        JOptionPane.showMessageDialog(
                null,
                e.getMessage()
        );
    }
    }//GEN-LAST:event_BackActionPerformed

    private void CetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CetakActionPerformed
        // TODO add your handling code here:
          try {

        boolean selesai =
        jTable2hasilkrs.print();

        if (selesai) {

            JOptionPane.showMessageDialog(
                this,
                "Hasil KRS berhasil dicetak!"
            );

        } else {

            JOptionPane.showMessageDialog(
                this,
                "Cetak dibatalkan"
            );
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
            this,
            "Gagal mencetak: "
            + e.getMessage()
        );
    }
    }//GEN-LAST:event_CetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() ->
    new HasilKRS("123")
            .setVisible(true)
);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Cetak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2RiwayatKRS;
    private javax.swing.JTable jTable2hasilkrs;
    // End of variables declaration//GEN-END:variables
}
