/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1.Mahasiswa;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.mycompany.mavenproject1.Koneksi;
/**
 *
 * @author user
 */
public class HasilKRS extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HasilKRS.class.getName());

    /**
     * Creates new form HasilKRS
     */
    
    
    
    private String nim;
    public HasilKRS(String nim) {
    initComponents();

    this.nim = nim;

    
    tampilData();
}
    
    private void tampilData() {

    DefaultTableModel model =
            new DefaultTableModel();

    model.addColumn("Kode MK");
    model.addColumn("Mata Kuliah");
    model.addColumn("SKS");
    model.addColumn("Status");

    jTable2hasilkrs.setModel(model);
    jTable2hasilkrs.setRowHeight(28);
    jTable2hasilkrs.setSelectionBackground(new java.awt.Color(26,86,160));
    jTable2hasilkrs.getTableHeader().setReorderingAllowed(false);
    jTable2hasilkrs.getTableHeader().setResizingAllowed(false);

    jTable2hasilkrs.getColumnModel().getColumn(0).setPreferredWidth(90);
    jTable2hasilkrs.getColumnModel().getColumn(1).setPreferredWidth(220);
    jTable2hasilkrs.getColumnModel().getColumn(2).setPreferredWidth(50);
    jTable2hasilkrs.getColumnModel().getColumn(3).setPreferredWidth(90);

    try {

        Connection conn =
                Koneksi.getConnection();

        String sql =
        "SELECT mk.kode_mk, " +
        "mk.nama_mk, " +
        "mk.sks, " +
        "k.status " +
        "FROM krs k " +
        "JOIN krs_detail kd " +
        "ON k.id_krs = kd.id_krs " +
        "JOIN kelas kl " +
        "ON kd.id_kelas = kl.id_kelas " +
        "JOIN mata_kuliah mk " +
        "ON kl.kode_mk = mk.kode_mk " +
        "WHERE k.nim = ? " +
        "ORDER BY k.id_krs DESC";

        PreparedStatement ps =
                conn.prepareStatement(sql);

        ps.setString(1, nim);

        ResultSet rs =
                ps.executeQuery();

        int totalSKS = 0;
        boolean adaData = false;

        while (rs.next()) {

    adaData = true;

    int sks = rs.getInt("sks");
    totalSKS += sks;

    model.addRow(new Object[]{
        rs.getString("kode_mk"),
        rs.getString("nama_mk"),
        sks,
        rs.getString("status")
         });
        }

    // Tampilkan total SKS dengan batas maksimal 23
    jLabel1.setText("Total SKS : " + totalSKS + " / 23");

    // Jika melebihi batas, tampilkan peringatan
    if (totalSKS > 23) {
    JOptionPane.showMessageDialog(
        this,
        "Total SKS melebihi batas maksimal (23 SKS)!",
        "Peringatan",
        JOptionPane.WARNING_MESSAGE
    );
    }

        jLabel1.setText("Total SKS : " + totalSKS);

        if (!adaData) {

            JOptionPane.showMessageDialog(
                null,
                "Belum ada data KRS"
            );
        }

    } catch(Exception e) {

        JOptionPane.showMessageDialog(
                null,
                e.getMessage()
        );
    }
}
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Back = new javax.swing.JButton();
        Cetak = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2hasilkrs = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Cetak.setText("Cetak");
        Cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CetakActionPerformed(evt);
            }
        });

        jTable2hasilkrs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2hasilkrs);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("HASIL KRS");

        jLabel1.setText("Informasi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Cetak)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Back)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(21, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cetak)
                    .addComponent(Back))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        try {

        Connection conn =
                Koneksi.getConnection();

        String sql =
        "SELECT m.nama, " +
        "m.semester, " +
        "p.nama_prodi " +
        "FROM mahasiswa m " +
        "LEFT JOIN prodi p " +
        "ON m.id_prodi = p.id_prodi " +
        "WHERE m.nim=?";

        PreparedStatement ps =
                conn.prepareStatement(sql);

        ps.setString(1, nim);

        ResultSet rs =
                ps.executeQuery();

        if(rs.next()) {

            String nama =
                    rs.getString("nama");

            String semester =
                    rs.getString("semester");

            String prodi =
                    rs.getString("nama_prodi");

            new Dahboard(
                    nim,
                    nama,
                    semester,
                    prodi
            ).setVisible(true);

            dispose();
        }

    } catch(Exception e) {

        JOptionPane.showMessageDialog(
                null,
                e.getMessage()
        );
    }
    }//GEN-LAST:event_BackActionPerformed

    private void CetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CetakActionPerformed
        // TODO add your handling code here:
          try {

        boolean selesai =
        jTable2hasilkrs.print();

        if (selesai) {

            JOptionPane.showMessageDialog(
                this,
                "Hasil KRS berhasil dicetak!"
            );

        } else {

            JOptionPane.showMessageDialog(
                this,
                "Cetak dibatalkan"
            );
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
            this,
            "Gagal mencetak: "
            + e.getMessage()
        );
    }
    }//GEN-LAST:event_CetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() ->
    new HasilKRS("123")
            .setVisible(true)
);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Cetak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2hasilkrs;
    // End of variables declaration//GEN-END:variables
}
