    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1.Mahasiswa;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.mycompany.mavenproject1.Koneksi;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
/**
 *
 * @author user
 */
public class IsiKrs extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(IsiKrs.class.getName());

    /**
     * Creates new form IsiKrs
     */
    public IsiKrs(String nim,
        String nama,
        String semester,
        String prodi) {
        initComponents();
        this.nim = nim;
        this.nama = nama;
        this.semester = semester;
        this.prodi = prodi;

    tampilMatkul();
}
    
    private String nim;
    private String nama;
    private String semester;
    private String prodi;
    

    private void hitungSKDipilih() {

    int totalDipilih = 0;

    for (int i = 0; i < jTable1.getRowCount(); i++) {

        Boolean pilih =
                (Boolean) jTable1.getValueAt(i, 0);

        if (pilih != null && pilih) {

            int sks = Integer.parseInt(
                    jTable1.getValueAt(i, 4)
                            .toString()
            );

            totalDipilih += sks;
        }
    }

    // tampil realtime
    sksdipilih.setText(
            String.valueOf(totalDipilih)
    );
}
    
    
    private void tampilMatkul() {

    DefaultTableModel model =
            new DefaultTableModel() {

        @Override
        public Class<?> getColumnClass(int column) {
            return column == 0
                    ? Boolean.class
                    : String.class;
        }

        @Override
        public boolean isCellEditable(
                int row,
                int column
        ) {
            return column == 0;
        }
    };

    model.addColumn("Pilih");
    model.addColumn("ID Kelas");
    model.addColumn("Kode MK");
    model.addColumn("Mata Kuliah");
    model.addColumn("SKS");

    jTable1.setModel(model);
    // realtime hitung sks saat checkbox dipilih
    model.addTableModelListener(
    new TableModelListener() {

    @Override
    public void tableChanged(
            TableModelEvent e
    ) {

        if (e.getColumn() == 0) {
            hitungSKDipilih();
        }
    }
    });

    String sql =
        "SELECT k.id_kelas, " +
        "mk.kode_mk, " +
        "mk.nama_mk, " +
        "mk.sks, " +
        "(k.kapasitas - k.jumlah_peserta) AS sisa_kursi " +
        "FROM kelas k " +
        "JOIN mata_kuliah mk ON k.kode_mk = mk.kode_mk " +
        "WHERE k.semester = ? " +
        "AND k.jumlah_peserta < k.kapasitas " +
        "ORDER BY mk.kode_mk";

    try (Connection conn = Koneksi.getConnection();
         PreparedStatement ps = conn.prepareStatement(sql)) {

        ps.setInt(1, Integer.parseInt(semester));

        try (ResultSet rs = ps.executeQuery()) {

            while (rs.next()) {

                model.addRow(new Object[]{
                    false,
                    rs.getString("id_kelas"),
                    rs.getString("kode_mk"),
                    rs.getString("nama_mk"),
                    rs.getInt("sks")
                });
            }
        }

        if (model.getRowCount() == 0) {

            JOptionPane.showMessageDialog(
                null,
                "Belum ada kelas tersedia untuk semester "
                + semester
            );
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                null,
                e.getMessage()
        );
    }
}   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TotalSKS = new javax.swing.JTextPane();
        Back = new javax.swing.JButton();
        Simpan = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        sksdipilih = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("ISI KRS");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Total SKS");

        jScrollPane2.setViewportView(TotalSKS);

        Back.setText("back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Simpan.setText("Simpan");
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(sksdipilih);

        jLabel3.setText("Sks dipilih ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Simpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Back))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(19, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Back)
                                    .addComponent(Simpan))
                                .addGap(0, 12, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel3)))
                        .addGap(12, 12, 12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        new Dahboard(
        nim,
        nama,
        semester,
        prodi
    ).setVisible(true);

    dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
            int totalSKS = 0;
        boolean adaPilihan = false;
 
        // hitung total sks
        for (int i = 0; i < jTable1.getRowCount(); i++) {
 
            Boolean pilih =
                (Boolean) jTable1.getValueAt(i, 0);
 
            if (pilih != null && pilih) {
 
                adaPilihan = true;
 
                int sks = Integer.parseInt(
                    jTable1.getValueAt(i, 4).toString()
                );
 
                totalSKS += sks;
            }
        }
 
        if (!adaPilihan) {
            JOptionPane.showMessageDialog(
                this,
                "Pilih minimal 1 mata kuliah!"
            );
            return;
        }
 
        // maksimal 24 sks
        if (totalSKS > 24) {
 
            JOptionPane.showMessageDialog(
                this,
                "Total SKS melebihi batas maksimal 24 SKS!"
            );
 
            return;
        }
 
        // tampil total sks
        TotalSKS.setText(String.valueOf(totalSKS));
 
        // FIX: seluruh proses sekarang dibungkus 1 transaksi.
        // Kalau ada error di tengah jalan (misalnya kelas keburu
        // penuh dan trigger MySQL menolak salah satu insert),
        // semua perubahan di-rollback, bukan cuma berhenti setengah jalan.
        Connection conn = null;
 
        try {
            conn = Koneksi.getConnection();
            conn.setAutoCommit(false);
 
            // cek apakah mahasiswa sudah pernah isi krs semester ini,
            // sekaligus ambil statusnya
            String cekKrs =
                "SELECT id_krs, status FROM krs " +
                "WHERE nim=? AND semester=?";
 
            int idKrs = 0;
 
            try (PreparedStatement psCek = conn.prepareStatement(cekKrs)) {
 
                psCek.setString(1, nim);
                psCek.setInt(2, Integer.parseInt(semester));
 
                try (ResultSet rsCek = psCek.executeQuery()) {
 
                    if (rsCek.next()) {
 
                        String statusSekarang = rsCek.getString("status");
 
                        // FIX: kalau KRS sudah diproses admin, jangan
                        // biarkan mahasiswa menambah/mengubah isi KRS lagi.
                        if ("Disetujui".equals(statusSekarang)
                                || "Ditolak".equals(statusSekarang)) {
 
                            JOptionPane.showMessageDialog(
                                this,
                                "KRS semester ini sudah diproses admin (status: "
                                + statusSekarang
                                + "). Tidak bisa diubah lagi."
                            );
                            conn.rollback();
                            return;
                        }
 
                        idKrs = rsCek.getInt("id_krs");
 
                    } else {
 
                        // simpan ke tabel krs
                        String sqlKrs =
                            "INSERT INTO krs " +
                            "(nim, semester, tahun_ajaran, status) " +
                            "VALUES (?, ?, ?, ?)";
 
                        try (PreparedStatement psKrs = conn.prepareStatement(
                                sqlKrs,
                                PreparedStatement.RETURN_GENERATED_KEYS
                        )) {
 
                            psKrs.setString(1, nim);
                            psKrs.setInt(2, Integer.parseInt(semester));
                            // TODO: ambil tahun ajaran aktif dari tabel/config,
                            // jangan hardcode.
                            psKrs.setString(3, "2025/2026");
                            psKrs.setString(4, "Menunggu");
 
                            psKrs.executeUpdate();
 
                            try (ResultSet generatedKeys = psKrs.getGeneratedKeys()) {
                                if (generatedKeys.next()) {
                                    idKrs = generatedKeys.getInt(1);
                                }
                            }
                        }
                    }
                }
            }
 
            // simpan matkul ke krs_detail
            String cekDetail =
                "SELECT 1 FROM krs_detail WHERE id_krs=? AND id_kelas=?";
            String sqlDetail =
                "INSERT INTO krs_detail (id_krs, id_kelas) VALUES (?, ?)";
 
            try (PreparedStatement psCekDetail = conn.prepareStatement(cekDetail);
                 PreparedStatement psDetail = conn.prepareStatement(sqlDetail)) {
 
                for (int i = 0; i < jTable1.getRowCount(); i++) {
 
                    Boolean pilih = (Boolean) jTable1.getValueAt(i, 0);
 
                    if (pilih != null && pilih) {
 
                        int idKelas = Integer.parseInt(
                            jTable1.getValueAt(i, 1).toString()
                        );
 
                        psCekDetail.setInt(1, idKrs);
                        psCekDetail.setInt(2, idKelas);
 
                        try (ResultSet rsDetail = psCekDetail.executeQuery()) {
                            if (rsDetail.next()) {
                                continue; // sudah ada, skip (anti-duplicate)
                            }
                        }
 
                        // Kalau kelas sudah penuh, trigger MySQL
                        // (trg_krs_detail_before_insert) akan melempar
                        // SQLException di sini -> ditangkap di catch bawah
                        // -> seluruh transaksi di-rollback.
                        psDetail.setInt(1, idKrs);
                        psDetail.setInt(2, idKelas);
                        psDetail.executeUpdate();
                    }
                }
            }
 
            conn.commit();
 
            JOptionPane.showMessageDialog(
                this,
                "KRS berhasil dikirim ke admin!"
            );
 
        } catch (Exception e) {
 
            try {
                if (conn != null) {
                    conn.rollback();
                }
            } catch (java.sql.SQLException rollbackEx) {
                logger.log(java.util.logging.Level.SEVERE, null, rollbackEx);
            }
 
            JOptionPane.showMessageDialog(
                this,
                "Gagal menyimpan KRS: " + e.getMessage()
            );
 
        } finally {
 
            try {
                if (conn != null) {
                    conn.setAutoCommit(true);
                }
            } catch (java.sql.SQLException ex) {
                logger.log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_SimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() ->
    new IsiKrs(
            "123",
            "Dummy",
            "1",
            "TI"
    ).setVisible(true)
);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Simpan;
    private javax.swing.JTextPane TotalSKS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextPane sksdipilih;
    // End of variables declaration//GEN-END:variables
}
