/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1.Mahasiswa;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.mycompany.mavenproject1.Koneksi;

/**
 *
 * @author user
 */
public class IsiKrs extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(IsiKrs.class.getName());

    /**
     * Creates new form IsiKrs
     */
    public IsiKrs(String nim,
        String nama,
        String semester,
        String prodi) {
        initComponents();
        this.nim = nim;
        this.nama = nama;
        this.semester = semester;
        this.prodi = prodi;

    tampilMatkul();
}
    
    private String nim;
    private String nama;
    private String semester;
    private String prodi;
    

    private void tampilMatkul() {

    DefaultTableModel model =
            new DefaultTableModel() {

        @Override
        public Class<?> getColumnClass(int column) {
            return column == 0
                    ? Boolean.class
                    : String.class;
        }

        @Override
        public boolean isCellEditable(
                int row,
                int column
        ) {
            return column == 0;
        }
    };

    model.addColumn("Pilih");
    model.addColumn("ID Kelas");
    model.addColumn("Kode MK");
    model.addColumn("Mata Kuliah");
    model.addColumn("SKS");

    jTable1.setModel(model);

    try {

        Connection conn =
                Koneksi.getConnection();

        String sql =
        "SELECT k.id_kelas, " +
        "mk.kode_mk, " +
        "mk.nama_mk, " +
        "mk.sks " +
        "FROM kelas k " +
        "JOIN mata_kuliah mk " +
        "ON k.kode_mk = mk.kode_mk " +
        "ORDER BY mk.kode_mk";

        PreparedStatement ps =
                conn.prepareStatement(sql);

        

        ResultSet rs =
                ps.executeQuery();

        while (rs.next()) {

            model.addRow(new Object[]{
                false,
                rs.getString("id_kelas"),
                rs.getString("kode_mk"),
                rs.getString("nama_mk"),
                rs.getInt("sks")
            });
        }

        if (model.getRowCount() == 0) {

            JOptionPane.showMessageDialog(
                null,
                "Belum ada kelas untuk semester "
                + semester
            );
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                null,
                e.getMessage()
        );
    }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TotalSKS = new javax.swing.JTextPane();
        Back = new javax.swing.JButton();
        Simpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("ISI KRS");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Total SKS");

        jScrollPane2.setViewportView(TotalSKS);

        Back.setText("back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Simpan.setText("Simpan");
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Simpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Back))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Back)
                                    .addComponent(Simpan)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel2)))
                        .addGap(6, 6, 6))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        new Dahboard(
        nim,
        nama,
        semester,
        prodi
).setVisible(true);

dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
        // TODO add your handling code here:
         try {

        Connection conn = Koneksi.getConnection();

        int totalSKS = 0;
        boolean adaPilihan = false;

        // hitung total sks
        for (int i = 0; i < jTable1.getRowCount(); i++) {

            Boolean pilih =
                (Boolean) jTable1.getValueAt(i, 0);

            if (pilih != null && pilih) {

                adaPilihan = true;

                int sks = Integer.parseInt(
                    jTable1.getValueAt(i, 4).toString()
                );

                totalSKS += sks;
            }
        }

        if (!adaPilihan) {
            JOptionPane.showMessageDialog(
                this,
                "Pilih minimal 1 mata kuliah!"
            );
            return;
        }

        // tampil total sks
        TotalSKS.setText(String.valueOf(totalSKS));

        // cek apakah mahasiswa sudah pernah isi krs semester ini
        String cekKrs =
            "SELECT id_krs FROM krs " +
            "WHERE nim=? AND semester=?";

        PreparedStatement psCek =
            conn.prepareStatement(cekKrs);

        psCek.setString(1, nim);
        psCek.setInt(2,
            Integer.parseInt(semester));

        ResultSet rsCek =
            psCek.executeQuery();

        int idKrs = 0;

        if (rsCek.next()) {

            idKrs =
                rsCek.getInt("id_krs");

        } else {

            // simpan ke tabel krs
            String sqlKrs =
                "INSERT INTO krs " +
                "(nim, semester, tahun_ajaran, status) " +
                "VALUES (?, ?, ?, ?)";

            PreparedStatement psKrs =
                conn.prepareStatement(
                    sqlKrs,
                    PreparedStatement.RETURN_GENERATED_KEYS
                );

            psKrs.setString(1, nim);
            psKrs.setInt(2,
                Integer.parseInt(semester));
            psKrs.setString(3,
                "2025/2026");
            psKrs.setString(4,
                "Menunggu");

            psKrs.executeUpdate();

            ResultSet generatedKeys =
                psKrs.getGeneratedKeys();

            if (generatedKeys.next()) {
                idKrs =
                    generatedKeys.getInt(1);
            }
        }

        // simpan matkul ke krs_detail
        for (int i = 0; i < jTable1.getRowCount(); i++) {

            Boolean pilih =
                (Boolean) jTable1.getValueAt(i, 0);

            if (pilih != null && pilih) {

                int idKelas =
                    Integer.parseInt(
                        jTable1
                        .getValueAt(i, 1)
                        .toString()
                    );

                // anti duplicate
                String cekDetail =
                    "SELECT * FROM krs_detail " +
                    "WHERE id_krs=? " +
                    "AND id_kelas=?";

                PreparedStatement psCekDetail =
                    conn.prepareStatement(
                        cekDetail
                    );

                psCekDetail.setInt(1, idKrs);
                psCekDetail.setInt(2, idKelas);

                ResultSet rsDetail =
                    psCekDetail.executeQuery();

                if (!rsDetail.next()) {

                    String sqlDetail =
                        "INSERT INTO krs_detail " +
                        "(id_krs, id_kelas) " +
                        "VALUES (?, ?)";

                    PreparedStatement psDetail =
                        conn.prepareStatement(
                            sqlDetail
                        );

                    psDetail.setInt(1, idKrs);
                    psDetail.setInt(2, idKelas);

                    psDetail.executeUpdate();
                }
            }
        }

        JOptionPane.showMessageDialog(
            this,
            "KRS berhasil dikirim ke admin!"
        );

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
            this,
            e.getMessage()
        );
    }
    }//GEN-LAST:event_SimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() ->
    new IsiKrs(
            "123",
            "Dummy",
            "1",
            "TI"
    ).setVisible(true)
);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Simpan;
    private javax.swing.JTextPane TotalSKS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
