/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1.Mahasiswa;

/**
 *
 * @author user
 */
public class JadwalKuliah extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JadwalKuliah.class.getName());

    /**
     * Creates new form JadwalKuliah
     */
    private String nim;
    private String nama;
    private String semester;
    private String prodi;
    public JadwalKuliah(
        String nim,
        String nama,
        String semester,
        String prodi) {

    initComponents();

    this.nim = nim;
    this.nama = nama;
    this.semester = semester;
    this.prodi = prodi;

    tampilJadwal();
}
    private void tampilJadwal() {

    javax.swing.table.DefaultTableModel model =
            new javax.swing.table.DefaultTableModel();

    model.addColumn("Hari");
    model.addColumn("Jam");
    model.addColumn("Kode MK");
    model.addColumn("Mata Kuliah");
    model.addColumn("SKS");
    model.addColumn("Ruangan");

    jTable1jadwalkuliah.setModel(model);

    try {

        java.sql.Connection conn =
                com.mycompany.mavenproject1.Koneksi
                        .getConnection();

        String sql =
        "SELECT j.hari, " +
        "j.jam_mulai, " +
        "j.jam_selesai, " +
        "mk.kode_mk, " +
        "mk.nama_mk, " +
        "mk.sks, " +
        "j.ruang " +
        "FROM krs k " +
        "JOIN krs_detail kd " +
        "ON k.id_krs = kd.id_krs " +
        "JOIN kelas kl " +
        "ON kd.id_kelas = kl.id_kelas " +
        "JOIN mata_kuliah mk " +
        "ON kl.kode_mk = mk.kode_mk " +
        "JOIN jadwal j " +
        "ON kl.id_kelas = j.id_kelas " +
        "WHERE k.nim=? " +
        "ORDER BY j.hari ASC";

        java.sql.PreparedStatement ps =
                conn.prepareStatement(sql);

        ps.setString(1, nim);

        java.sql.ResultSet rs =
                ps.executeQuery();

        while(rs.next()) {

            String jam =
                    rs.getString("jam_mulai")
                    + " - " +
                    rs.getString("jam_selesai");

            model.addRow(new Object[]{

                rs.getString("hari"),
                jam,
                rs.getString("kode_mk"),
                rs.getString("nama_mk"),
                rs.getInt("sks"),
                rs.getString("ruang")
            });
        }

    } catch(Exception e) {

        javax.swing.JOptionPane.showMessageDialog(
                null,
                e.getMessage()
        );
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1jadwalkuliah = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Informasi Jadwal");

        jTable1jadwalkuliah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1jadwalkuliah);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 316, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Dahboard(
            nim,
            nama,
            semester,
            prodi
    ).setVisible(true);

    dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() ->
    new JadwalKuliah(
        "123",
        "Dummy",
        "1",
        "Teknik Informatika"
).setVisible(true)
);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1jadwalkuliah;
    // End of variables declaration//GEN-END:variables
}
