/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1.Mahasiswa;
import java.awt.*;
import javax.swing.*;
/**
 *
 * @author user
 */
public class ProfilMahasiswa extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProfilMahasiswa.class.getName());

    /**
     * Creates new form ProfilMahasiswa
     */
    
    private String nim;
    private String nama;
    private String semester;
    private String prodi;

    public ProfilMahasiswa(String nim,
                           String nama,
                           String semester,
                           String prodi) {

        this.nim = nim;
        this.nama = nama;
        this.semester = semester;
        this.prodi = prodi;

        initUI();
    }

    private void initUI() {

        setTitle("Profil Mahasiswa");
        setSize(450, 300);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        JPanel panel = new JPanel();
        panel.setLayout(new BorderLayout(10,10));

        JLabel judul = new JLabel(
                "PROFIL MAHASISWA",
                SwingConstants.CENTER
        );

        judul.setFont(new Font("Segoe UI", Font.BOLD, 20));

        JTextArea area = new JTextArea();

        area.setEditable(false);
        area.setFont(new Font("Consolas", Font.PLAIN, 15));

        area.setText(
                "\n" +
                "=================================\n" +
                "         DATA MAHASISWA\n" +
                "=================================\n\n" +
                "NIM      : " + nim + "\n\n" +
                "Nama     : " + nama + "\n\n" +
                "Prodi    : " + prodi + "\n\n" +
                "Semester : " + semester + "\n\n" +
                "================================="
        );

        JButton btnKembali = new JButton("Kembali");

        btnKembali.addActionListener(e -> {

            new Dahboard(
                    nim,
                    nama,
                    semester,
                    prodi
            ).setVisible(true);

            dispose();
        });

        panel.add(judul, BorderLayout.NORTH);
        panel.add(new JScrollPane(area), BorderLayout.CENTER);
        panel.add(btnKembali, BorderLayout.SOUTH);

        add(panel);
    }

    public static void main(String[] args) {

        new ProfilMahasiswa(
                "24110030",
                "Alvin",
                "4",
                "Informatika"
        ).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
