/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package krs;

import com.mycompany.mavenproject1.FormAdmin;
import com.mycompany.mavenproject1.database;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nicos
 */
public class FormKRS extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormKRS.class.getName());

    /**
     * Creates new form FormKRS
     */
    public FormKRS() {
        initComponents();
        jTable1.setDefaultEditor(Object.class, null);
        loadData();
    }
    private void loadData() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID KRS");
    model.addColumn("NIM");
    model.addColumn("Nama Mahasiswa");
    model.addColumn("Semester");
    model.addColumn("Tahun Ajaran");
    model.addColumn("Status");

    database db = new database();
    try (Connection con = db.koneksi();
         Statement st = con.createStatement();
         ResultSet rs = st.executeQuery(
             "SELECT id_krs, nim, nama_mahasiswa, semester, " +
             "tahun_ajaran, status FROM v_krs_lengkap " +
             "GROUP BY id_krs, nim, nama_mahasiswa, semester, tahun_ajaran, status " +
             "ORDER BY id_krs DESC")) {

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id_krs"),
                rs.getString("nim"),
                rs.getString("nama_mahasiswa"),
                rs.getInt("semester"),
                rs.getString("tahun_ajaran"),
                rs.getString("status")
            });
        }

    } catch (SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Error: " + e.getMessage(), "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }

    jTable1.setModel(model);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        Setujui = new javax.swing.JButton();
        Tolak = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Form KRS");

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Setujui.setText("Setujui");
        Setujui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetujuiActionPerformed(evt);
            }
        });

        Tolak.setText("Tolak");
        Tolak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TolakActionPerformed(evt);
            }
        });

        Hapus.setText("Hapus");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Back)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Setujui)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Tolak)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Hapus))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Setujui)
                    .addComponent(Tolak)
                    .addComponent(Hapus))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        new FormAdmin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void SetujuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetujuiActionPerformed
        int baris = jTable1.getSelectedRow();
        if (baris == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Pilih KRS terlebih dahulu!",
                "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idKrs = (int) jTable1.getValueAt(baris, 0);
        String status = (String) jTable1.getValueAt(baris, 5);

        if (status.equals("Disetujui")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "KRS ini sudah disetujui!", "Info",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        database db = new database();
        try (Connection con = db.koneksi();
             PreparedStatement ps = con.prepareStatement(
                 "UPDATE krs SET status='Disetujui' WHERE id_krs=?")) {

            ps.setInt(1, idKrs);
            ps.executeUpdate();
            javax.swing.JOptionPane.showMessageDialog(this,
                "KRS berhasil disetujui!", "Sukses",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
            loadData();

        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error: " + e.getMessage(), "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_SetujuiActionPerformed

    private void TolakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TolakActionPerformed
        int baris = jTable1.getSelectedRow();
        if (baris == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Pilih KRS terlebih dahulu!",
                "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idKrs = (int) jTable1.getValueAt(baris, 0);
        String status = (String) jTable1.getValueAt(baris, 5);

        if (status.equals("Ditolak")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "KRS ini sudah ditolak!", "Info",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        String catatan = javax.swing.JOptionPane.showInputDialog(this,
            "Masukkan alasan penolakan (opsional):",
            "Tolak KRS", javax.swing.JOptionPane.QUESTION_MESSAGE);

        if (catatan == null) return;

        database db = new database();
        try (Connection con = db.koneksi();
             PreparedStatement ps = con.prepareStatement(
                 "UPDATE krs SET status='Ditolak', catatan=? WHERE id_krs=?")) {

            ps.setString(1, catatan.isEmpty() ? null : catatan);
            ps.setInt(2, idKrs);
            ps.executeUpdate();
            javax.swing.JOptionPane.showMessageDialog(this,
                "KRS berhasil ditolak!", "Sukses",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
            loadData();

        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error: " + e.getMessage(), "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_TolakActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        int baris = jTable1.getSelectedRow();
        if (baris == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Pilih KRS terlebih dahulu!",
                "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this,
            "Yakin ingin menghapus KRS ini?",
            "Konfirmasi Hapus", javax.swing.JOptionPane.YES_NO_OPTION);

        if (konfirmasi != javax.swing.JOptionPane.YES_OPTION) return;

        int idKrs = (int) jTable1.getValueAt(baris, 0);

        database db = new database();
        try (Connection con = db.koneksi();
             PreparedStatement ps = con.prepareStatement(
                 "DELETE FROM krs WHERE id_krs=?")) {

            ps.setInt(1, idKrs);
            ps.executeUpdate();
            javax.swing.JOptionPane.showMessageDialog(this,
                "KRS berhasil dihapus!", "Sukses",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
            loadData();

        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error: " + e.getMessage(), "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_HapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormKRS().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Hapus;
    private javax.swing.JButton Setujui;
    private javax.swing.JButton Tolak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
