/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form_Dosen;

import com.mycompany.mavenproject1.Mahasiswa.*;

/**
 *
 * @author nicos
 */
public class FormDosen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormDosen.class.getName());

    /**
     * Creates new form FormMahasiswa
     */
    public FormDosen() {
        initComponents();
        tbMahasiswa.setDefaultEditor(Object.class, null);
        loadProdi();
        loadData();
        tbMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pilihBaris();
            }
        });
    }
    
    private void loadProdi() {
        comboProdi.removeAllItems();
        com.mycompany.mavenproject1.database db = new com.mycompany.mavenproject1.database();
        try (java.sql.Connection con = db.koneksi();
             java.sql.Statement st = con.createStatement();
             java.sql.ResultSet rs = st.executeQuery("SELECT id_prodi, nama_prodi FROM prodi")) {
            while (rs.next()) {
                comboProdi.addItem(rs.getInt("id_prodi") + " - " + rs.getString("nama_prodi"));
            }
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Gagal load prodi: " + e.getMessage(), "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void loadData() {
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
        new String[]{"ID", "NIDN", "Nama Dosen", "Prodi"}, 0
    ) {
        public boolean isCellEditable(int row, int col) { return false; }
    };

        com.mycompany.mavenproject1.database db = new com.mycompany.mavenproject1.database();
        try (java.sql.Connection con = db.koneksi();
             java.sql.Statement st = con.createStatement();
             java.sql.ResultSet rs = st.executeQuery(
                 "SELECT d.id_dosen, d.nidn, d.nama_dosen, p.nama_prodi " +
                 "FROM dosen d LEFT JOIN prodi p ON d.id_prodi = p.id_prodi")) {
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id_dosen"),
                    rs.getString("nidn"),
                    rs.getString("nama_dosen"),
                    rs.getString("nama_prodi")
                });
            }
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error: " + e.getMessage(), "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        tbMahasiswa.setModel(model);
    }

    private void pilihBaris() {
        int baris = tbMahasiswa.getSelectedRow();
        if (baris == -1) return;

        int idDosen = (int) tbMahasiswa.getValueAt(baris, 0);

        com.mycompany.mavenproject1.database db = new com.mycompany.mavenproject1.database();
        try (java.sql.Connection con = db.koneksi();
             java.sql.PreparedStatement ps = con.prepareStatement(
                 "SELECT d.*, p.nama_prodi FROM dosen d " +
                 "LEFT JOIN prodi p ON d.id_prodi = p.id_prodi WHERE d.id_dosen = ?")) {
            ps.setInt(1, idDosen);
            java.sql.ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                fieldNidn.setText(rs.getString("nidn"));
                fieldNama.setText(rs.getString("nama_dosen"));
                fieldPassword.setText(rs.getString("password"));

                int idProdi = rs.getInt("id_prodi");
                for (int i = 0; i < comboProdi.getItemCount(); i++) {
                    if (comboProdi.getItemAt(i).startsWith(idProdi + " -")) {
                        comboProdi.setSelectedIndex(i);
                        break;
                    }
                }
            }
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error: " + e.getMessage(), "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void bersihForm() {
        fieldNidn.setText("");
        fieldNama.setText("");
        fieldPassword.setText("");
        if (comboProdi.getItemCount() > 0) comboProdi.setSelectedIndex(0);
        tbMahasiswa.clearSelection();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelNidn = new javax.swing.JLabel();
        fieldNidn = new javax.swing.JTextField();
        labelNama = new javax.swing.JLabel();
        fieldNama = new javax.swing.JTextField();
        labelPassword = new javax.swing.JLabel();
        fieldPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        comboProdi = new javax.swing.JComboBox<>();
        btnTambah = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBersih = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMahasiswa = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        jLabel1.setText("FORM DOSEN");

        labelNidn.setText("NIDN :");

        labelNama.setText("Nama :");

        labelPassword.setText("Password :");

        jLabel2.setText("Prodi :");

        comboProdi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnBersih.setText("Bersih");
        btnBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBersihActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(tbMahasiswa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnHapus)
                                .addGap(18, 18, 18)
                                .addComponent(btnBersih))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTambah)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdate))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Back)
                                .addGap(235, 235, 235)
                                .addComponent(jLabel1)))
                        .addContainerGap(379, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(38, 38, 38)
                                .addComponent(comboProdi, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelPassword)
                                .addGap(18, 18, 18)
                                .addComponent(fieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelNama)
                                    .addComponent(labelNidn))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldNidn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back)
                    .addComponent(jLabel1))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNidn)
                            .addComponent(fieldNidn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNama)
                            .addComponent(fieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPassword)
                            .addComponent(fieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(comboProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnUpdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapus)
                    .addComponent(btnBersih))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        new com.mycompany.mavenproject1.FormAdmin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        String nidn     = fieldNidn.getText().trim();
        String nama     = fieldNama.getText().trim();
        String password = new String(fieldPassword.getPassword()).trim();
        String prodiItem = (String) comboProdi.getSelectedItem();

        if (nidn.isEmpty() || nama.isEmpty() || password.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "NIDN, Nama, dan Password harus diisi!", "Peringatan",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idProdi = Integer.parseInt(prodiItem.split(" - ")[0]);

        com.mycompany.mavenproject1.database db = new com.mycompany.mavenproject1.database();
        try (java.sql.Connection con = db.koneksi()) {

            // Cek NIDN duplikat
            java.sql.PreparedStatement cek = con.prepareStatement(
                "SELECT COUNT(*) FROM dosen WHERE nidn = ?");
            cek.setString(1, nidn);
            java.sql.ResultSet rs = cek.executeQuery();
            if (rs.next() && rs.getInt(1) > 0) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "NIDN sudah terdaftar!", "Peringatan",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            java.sql.PreparedStatement ps = con.prepareStatement(
                "INSERT INTO dosen (nidn, nama_dosen, password, id_prodi) VALUES (?, ?, ?, ?)");
            ps.setString(1, nidn);
            ps.setString(2, nama);
            ps.setString(3, password);
            ps.setInt(4, idProdi);
            ps.executeUpdate();

            javax.swing.JOptionPane.showMessageDialog(this,
                "Dosen berhasil ditambahkan!", "Sukses",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
            bersihForm();
            loadData();

        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error: " + e.getMessage(), "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String nidn     = fieldNidn.getText().trim();
        String nama     = fieldNama.getText().trim();
        String password = new String(fieldPassword.getPassword()).trim();
        String prodiItem = (String) comboProdi.getSelectedItem();

        if (nidn.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Pilih data dari tabel terlebih dahulu!", "Peringatan",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idProdi = Integer.parseInt(prodiItem.split(" - ")[0]);

        com.mycompany.mavenproject1.database db = new com.mycompany.mavenproject1.database();
        try (java.sql.Connection con = db.koneksi()) {

            java.sql.PreparedStatement ps;
            if (password.isEmpty()) {
                ps = con.prepareStatement(
                    "UPDATE dosen SET nama_dosen=?, id_prodi=? WHERE nidn=?");
                ps.setString(1, nama);
                ps.setInt(2, idProdi);
                ps.setString(3, nidn);
            } else {
                ps = con.prepareStatement(
                    "UPDATE dosen SET nama_dosen=?, password=?, id_prodi=? WHERE nidn=?");
                ps.setString(1, nama);
                ps.setString(2, password);
                ps.setInt(3, idProdi);
                ps.setString(4, nidn);
            }
            ps.executeUpdate();

            javax.swing.JOptionPane.showMessageDialog(this,
                "Data dosen berhasil diupdate!", "Sukses",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
            bersihForm();
            loadData();

        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error: " + e.getMessage(), "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        String nidn = fieldNidn.getText().trim();
        if (nidn.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Pilih data dari tabel terlebih dahulu!", "Peringatan",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this,
            "Yakin ingin menghapus dosen dengan NIDN " + nidn + "?",
            "Konfirmasi Hapus", javax.swing.JOptionPane.YES_NO_OPTION);
        if (konfirmasi != javax.swing.JOptionPane.YES_OPTION) return;

        com.mycompany.mavenproject1.database db = new com.mycompany.mavenproject1.database();
        try (java.sql.Connection con = db.koneksi();
             java.sql.PreparedStatement ps = con.prepareStatement(
                 "DELETE FROM dosen WHERE nidn = ?")) {
            ps.setString(1, nidn);
            ps.executeUpdate();

            javax.swing.JOptionPane.showMessageDialog(this,
                "Data dosen berhasil dihapus!", "Sukses",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
            bersihForm();
            loadData();

        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error: " + e.getMessage(), "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBersihActionPerformed
        bersihForm();
    }//GEN-LAST:event_btnBersihActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormDosen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton btnBersih;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> comboProdi;
    private javax.swing.JTextField fieldNama;
    private javax.swing.JTextField fieldNidn;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelNidn;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JTable tbMahasiswa;
    // End of variables declaration//GEN-END:variables
}
