/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jadwal;
import com.mycompany.mavenproject1.database;
import java.sql.*;

/**
 *
 * @author nicos
 */
public class TambahJadwal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TambahJadwal.class.getName());

    /**
     * Creates new form TambahJadwal
     */
    public TambahJadwal() {
        initComponents();
        loadKelas();
        loadHari();
    }
    
    private void loadKelas() {
        comboKelas.removeAllItems();
        database db = new database();
        try (Connection con = db.koneksi();
             Statement st = con.createStatement();
             ResultSet rs = st.executeQuery(
                 "SELECT k.id_kelas, mk.nama_mk FROM kelas k " +
                 "JOIN mata_kuliah mk ON k.kode_mk = mk.kode_mk " +
                 "ORDER BY k.id_kelas")) {

            while (rs.next()) {
                comboKelas.addItem(rs.getInt("id_kelas") + " - " + rs.getString("nama_mk"));
            }

        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error: " + e.getMessage(), "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void loadHari() {
        comboHari.removeAllItems();
        comboHari.addItem("Senin");
        comboHari.addItem("Selasa");
        comboHari.addItem("Rabu");
        comboHari.addItem("Kamis");
        comboHari.addItem("Jumat");
        comboHari.addItem("Sabtu");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelKelas = new javax.swing.JLabel();
        comboKelas = new javax.swing.JComboBox<>();
        labelHari = new javax.swing.JLabel();
        comboHari = new javax.swing.JComboBox<>();
        labelMulai = new javax.swing.JLabel();
        fieldMulai = new javax.swing.JTextField();
        labelSelesai = new javax.swing.JLabel();
        fieldSelesai = new javax.swing.JTextField();
        labelRuang = new javax.swing.JLabel();
        fieldRuang = new javax.swing.JTextField();
        Tambah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Tambah Jadwal");

        labelKelas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelKelas.setText("Kelas");

        labelHari.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelHari.setText("labelHari");

        labelMulai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelMulai.setText("Jam Mulai");

        labelSelesai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelSelesai.setText("Jam Selesai");

        labelRuang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelRuang.setText("Ruang");

        Tambah.setBackground(new java.awt.Color(26, 86, 160));
        Tambah.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Tambah.setForeground(new java.awt.Color(255, 255, 255));
        Tambah.setText("Tambah Data");
        Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Back))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelKelas)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(comboKelas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldSelesai)
                    .addComponent(comboHari, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fieldMulai)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelHari)
                            .addComponent(labelMulai)
                            .addComponent(labelSelesai)
                            .addComponent(labelRuang))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(fieldRuang))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(Tambah)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(labelKelas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelHari)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelMulai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSelesai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelRuang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldRuang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        new FormJadwal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahActionPerformed
        // Ambil id_kelas dari combobox
        String selectedKelas = comboKelas.getSelectedItem().toString();
        int idKelas = Integer.parseInt(selectedKelas.split(" - ")[0]);

        String hari     = comboHari.getSelectedItem().toString();
        String jamMulai = fieldMulai.getText().trim();
        String jamSel   = fieldSelesai.getText().trim();
        String ruang    = fieldRuang.getText().trim();

        // Validasi
        if (jamMulai.isEmpty() || jamSel.isEmpty() || ruang.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Semua field harus diisi!",
                "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validasi format jam (HH:mm)
        if (!jamMulai.matches("\\d{2}:\\d{2}") || !jamSel.matches("\\d{2}:\\d{2}")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Format jam harus HH:mm, contoh: 08:00",
                "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        database db = new database();
        try (Connection con = db.koneksi();
             PreparedStatement ps = con.prepareStatement(
                 "INSERT INTO jadwal (id_kelas, hari, jam_mulai, jam_selesai, ruang) " +
                 "VALUES (?, ?, ?, ?, ?)")) {

            ps.setInt(1, idKelas);
            ps.setString(2, hari);
            ps.setString(3, jamMulai);
            ps.setString(4, jamSel);
            ps.setString(5, ruang);
            ps.executeUpdate();

            javax.swing.JOptionPane.showMessageDialog(this,
                "Jadwal berhasil ditambahkan!", "Sukses",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);

            new FormJadwal().setVisible(true);
            this.dispose();

        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error: " + e.getMessage(), "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_TambahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TambahJadwal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Tambah;
    private javax.swing.JComboBox<String> comboHari;
    private javax.swing.JComboBox<String> comboKelas;
    private javax.swing.JTextField fieldMulai;
    private javax.swing.JTextField fieldRuang;
    private javax.swing.JTextField fieldSelesai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelHari;
    private javax.swing.JLabel labelKelas;
    private javax.swing.JLabel labelMulai;
    private javax.swing.JLabel labelRuang;
    private javax.swing.JLabel labelSelesai;
    // End of variables declaration//GEN-END:variables
}
