/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kelas;

import com.mycompany.mavenproject1.FormAdmin;
import com.mycompany.mavenproject1.User.FormUser;

/**
 *
 * @author User
 */
public class FormKelas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormKelas.class.getName());

    /**
     * Creates new form FormKelas
     */
    public FormKelas() {
    initComponents();

    loadComboBox(); // wajib

    loadData();

    tblKelas.getSelectionModel()
        .addListSelectionListener(
            new javax.swing.event.ListSelectionListener() {

        public void valueChanged(
                javax.swing.event.ListSelectionEvent evt) {

            isiFormDariTabel();
        }
    });
}
    
    private void loadComboBox() {

    jComboBox1.removeAllItems();
    jComboBox2.removeAllItems();

    try {
        java.sql.Connection c = getConn();

        String sqlMK =
            "SELECT kode_mk, nama_mk FROM mata_kuliah";

        java.sql.Statement stMK =
            c.createStatement();

        java.sql.ResultSet rsMK =
            stMK.executeQuery(sqlMK);

        while (rsMK.next()) {

            jComboBox1.addItem(
                rsMK.getString("kode_mk")
                + " - "
                + rsMK.getString("nama_mk")
            );
        }

        String sqlDosen =
            "SELECT id_dosen, nama_dosen FROM dosen";

        java.sql.Statement stDosen =
            c.createStatement();

        java.sql.ResultSet rsDosen =
            stDosen.executeQuery(sqlDosen);

        while (rsDosen.next()) {

            jComboBox2.addItem(
                rsDosen.getInt("id_dosen")
                + " - "
                + rsDosen.getString("nama_dosen")
            );
        }

        c.close();

    } catch (Exception e) {

        javax.swing.JOptionPane.showMessageDialog(
            this,
            e.getMessage()
        );
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textArea1 = new java.awt.TextArea();
        lblHeader = new java.awt.Label();
        lblIdKelas = new java.awt.Label();
        txtIdKelas = new java.awt.TextField();
        lblKodeMK = new java.awt.Label();
        lblIdDosen = new java.awt.Label();
        lblTahunAjaran = new java.awt.Label();
        txtTahunAjaran = new java.awt.TextField();
        lblSemester = new java.awt.Label();
        txtSemester = new java.awt.TextField();
        lblHari = new java.awt.Label();
        cbHari = new javax.swing.JComboBox<>();
        lblJamMulai = new java.awt.Label();
        txtJamMulai = new java.awt.TextField();
        lblJamSelesai = new java.awt.Label();
        txtJamSelesai = new java.awt.TextField();
        lblRuang = new java.awt.Label();
        txtRuang = new java.awt.TextField();
        btnTambah = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        Bersih = new javax.swing.JButton();
        jScrollPane1 = new java.awt.ScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKelas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHeader.setText("SISTEM KRS");

        lblIdKelas.setText("ID Kelas :");

        txtIdKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdKelasActionPerformed(evt);
            }
        });

        lblKodeMK.setText("Kode MK :");

        lblIdDosen.setText("ID Dosen :");

        lblTahunAjaran.setText("Thn Ajaran :");

        lblSemester.setText("Semester :");

        lblHari.setText("Hari :");

        cbHari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Senin", "Selasa", "Rabu", "Kamis", "Jumat" }));
        cbHari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHariActionPerformed(evt);
            }
        });

        lblJamMulai.setText("Jam Mulai :");

        txtJamMulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJamMulaiActionPerformed(evt);
            }
        });

        lblJamSelesai.setText("Jam Selesai :");

        lblRuang.setText("Ruang :");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapos");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        Bersih.setText("Bersih");
        Bersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BersihActionPerformed(evt);
            }
        });

        tblKelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblKelas);

        jScrollPane1.add(jScrollPane2);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(340, Short.MAX_VALUE)
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(283, 283, 283))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRuang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addGap(92, 92, 92))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblIdKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtIdKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(btnTambah)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnUpdate))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(btnHapus)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Bersih))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblTahunAjaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTahunAjaran, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtJamSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbHari, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtRuang, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(lblJamSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblJamMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtJamMulai, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblIdDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, 0, 105, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblKodeMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblIdKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTahunAjaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTahunAjaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblJamMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJamMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblJamSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJamSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRuang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRuang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKodeMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnUpdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapus)
                    .addComponent(Bersih))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdKelasActionPerformed
    txtIdKelas.setText("");
    txtIdKelas.setEditable(false);
    }//GEN-LAST:event_txtIdKelasActionPerformed

    private void cbHariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbHariActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
    java.sql.Connection c = null;
    try {
    c = getConn();
    c.setAutoCommit(false);
    java.sql.PreparedStatement psK = c.prepareStatement(
        "INSERT INTO kelas (kode_mk, id_dosen, tahun_ajaran, semester) VALUES (?,?,?,?)",
        java.sql.Statement.RETURN_GENERATED_KEYS);
    String kodeMK =
    jComboBox1.getSelectedItem()
    .toString()
    .split(" - ")[0];

    int idDosen =
    Integer.parseInt(
        jComboBox2.getSelectedItem()
        .toString()
        .split(" - ")[0]
    );

    psK.setString(1, kodeMK);
    psK.setInt(2, idDosen);
    psK.setString(3, txtTahunAjaran.getText());
    psK.setString(4, txtSemester.getText());
    psK.executeUpdate();
    java.sql.ResultSet gk = psK.getGeneratedKeys();
    int idBaru = 0;
    if (gk.next()) idBaru = gk.getInt(1);
    java.sql.PreparedStatement psJ = c.prepareStatement(
        "INSERT INTO jadwal (id_kelas, hari, jam_mulai, jam_selesai, ruang) VALUES (?,?,?,?,?)");
    psJ.setInt(1, idBaru);
    psJ.setString(2, cbHari.getSelectedItem().toString());
    psJ.setString(3, txtJamMulai.getText());
    psJ.setString(4, txtJamSelesai.getText());
    psJ.setString(5, txtRuang.getText());
    psJ.executeUpdate();
    c.commit();
    javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");
    
    
    bersihForm();
    loadData();
    c.close();
} catch (java.sql.SQLException ex) {
    try { if (c != null) c.rollback(); } catch (java.sql.SQLException ignored) {}
    javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
    if (txtIdKelas.getText().isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "Pilih data di tabel dulu!");
    return;
}
java.sql.Connection c = null;
try {
    c = getConn();
    c.setAutoCommit(false);
    int idK = Integer.parseInt(txtIdKelas.getText());
    java.sql.PreparedStatement psK = c.prepareStatement(
        "UPDATE kelas SET kode_mk=?, id_dosen=?, tahun_ajaran=?, semester=? WHERE id_kelas=?");
    String kodeMK =
    jComboBox1.getSelectedItem()
        .toString()
        .split(" - ")[0];

        int idDosen =
        Integer.parseInt(
    jComboBox2.getSelectedItem()
    .toString()
    .split(" - ")[0]
    );

    psK.setString(1, kodeMK);
    psK.setInt(2, idDosen);
    psK.setString(3, txtTahunAjaran.getText());
    psK.setString(4, txtSemester.getText());
    psK.setInt(5, idK);
    psK.executeUpdate();
    java.sql.PreparedStatement psJ = c.prepareStatement(
        "UPDATE jadwal SET hari=?, jam_mulai=?, jam_selesai=?, ruang=? WHERE id_kelas=?");
    psJ.setString(1, cbHari.getSelectedItem().toString());
    psJ.setString(2, txtJamMulai.getText());
    psJ.setString(3, txtJamSelesai.getText());
    psJ.setString(4, txtRuang.getText());
    psJ.setInt(5, idK);
    psJ.executeUpdate();
    c.commit();
    javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil diupdate!");
    bersihForm();
    loadData();
    c.close();
} catch (java.sql.SQLException ex) {
    try { if (c != null) c.rollback(); } catch (java.sql.SQLException ignored) {}
    javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
    if (txtIdKelas.getText().isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "Pilih data di tabel dulu!");
    return;
}
int pilih = javax.swing.JOptionPane.showConfirmDialog(this, "Yakin hapus data ini?");
if (pilih == javax.swing.JOptionPane.YES_OPTION) {
    java.sql.Connection c = null;
    try {
        c = getConn();
        c.setAutoCommit(false);
        int idK = Integer.parseInt(txtIdKelas.getText());
        java.sql.PreparedStatement psJ = c.prepareStatement("DELETE FROM jadwal WHERE id_kelas=?");
        psJ.setInt(1, idK);
        psJ.executeUpdate();
        java.sql.PreparedStatement psK = c.prepareStatement("DELETE FROM kelas WHERE id_kelas=?");
        psK.setInt(1, idK);
        psK.executeUpdate();
        c.commit();
        javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
        bersihForm();
        loadData();
        c.close();
    } catch (java.sql.SQLException ex) {
        try { if (c != null) c.rollback(); } catch (java.sql.SQLException ignored) {}
        javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage());
    }
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void BersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BersihActionPerformed
    bersihForm();        // TODO add your handling code here:
    }//GEN-LAST:event_BersihActionPerformed

    private void txtJamMulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJamMulaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJamMulaiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    new FormAdmin().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormKelas().setVisible(true));
    }
    private void loadData() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblKelas.getModel();
        model.setRowCount(0);
        model.setColumnIdentifiers(new String[]{"ID Kelas","Kode MK","ID Dosen","Thn Ajaran","Semester","Hari","Jam Mulai","Jam Selesai","Ruang"});
        String sql = "SELECT k.id_kelas, k.kode_mk, k.id_dosen, k.tahun_ajaran, k.semester, "
                   + "j.hari, j.jam_mulai, j.jam_selesai, j.ruang "
                   + "FROM kelas k LEFT JOIN jadwal j ON k.id_kelas = j.id_kelas";
        try {
            java.sql.Connection c = getConn();
            java.sql.Statement s = c.createStatement();
            java.sql.ResultSet r = s.executeQuery(sql);
            while (r.next()) {
                model.addRow(new Object[]{
                    r.getInt("id_kelas"),
                    r.getString("kode_mk"),
                    r.getInt("id_dosen"),
                    r.getString("tahun_ajaran"),
                    r.getString("semester"),
                    r.getString("hari"),
                    r.getString("jam_mulai"),
                    r.getString("jam_selesai"),
                    r.getString("ruang")
                });
            }
            c.close();
        } catch (java.sql.SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private java.sql.Connection getConn() throws java.sql.SQLException {
        return java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/krs", "root", "");
    }

    private void bersihForm() {
        txtIdKelas.setText("");
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        txtTahunAjaran.setText("");
        txtSemester.setText("");
        cbHari.setSelectedIndex(0);
        txtJamMulai.setText("");
        txtJamSelesai.setText("");
        txtRuang.setText("");
        tblKelas.clearSelection();
    }

    private void isiFormDariTabel() {
        int row = tblKelas.getSelectedRow();
        if (row >= 0) {
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblKelas.getModel();
            txtIdKelas.setText(model.getValueAt(row, 0).toString());
            String kodeMK =
    model.getValueAt(row,1)
    .toString();

    for (int i = 0;
     i < jComboBox1.getItemCount();
     i++) {

    if (jComboBox1
        .getItemAt(i)
        .startsWith(kodeMK)) {

        jComboBox1
            .setSelectedIndex(i);
        break;
          }
        }

        String idDosen =
        model.getValueAt(row,2)
          .toString();

        for (int i = 0;
           i < jComboBox2.getItemCount();
          i++) {

             if (jComboBox2
               .getItemAt(i)
                .startsWith(idDosen)) {

                   jComboBox2
                   .setSelectedIndex(i);
                   break;
             }
            }
            txtTahunAjaran.setText(model.getValueAt(row, 3).toString());
            txtSemester.setText(model.getValueAt(row, 4).toString());
            Object hari = model.getValueAt(row, 5);
            if (hari != null) cbHari.setSelectedItem(hari.toString());
            Object jm = model.getValueAt(row, 6);
            txtJamMulai.setText(jm != null ? jm.toString() : "");
            Object js = model.getValueAt(row, 7);
            txtJamSelesai.setText(js != null ? js.toString() : "");
            Object ruang = model.getValueAt(row, 8);
            txtRuang.setText(ruang != null ? ruang.toString() : "");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bersih;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbHari;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private java.awt.ScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label lblHari;
    private java.awt.Label lblHeader;
    private java.awt.Label lblIdDosen;
    private java.awt.Label lblIdKelas;
    private java.awt.Label lblJamMulai;
    private java.awt.Label lblJamSelesai;
    private java.awt.Label lblKodeMK;
    private java.awt.Label lblRuang;
    private java.awt.Label lblSemester;
    private java.awt.Label lblTahunAjaran;
    private javax.swing.JTable tblKelas;
    private java.awt.TextArea textArea1;
    private java.awt.TextField txtIdKelas;
    private java.awt.TextField txtJamMulai;
    private java.awt.TextField txtJamSelesai;
    private java.awt.TextField txtRuang;
    private java.awt.TextField txtSemester;
    private java.awt.TextField txtTahunAjaran;
    // End of variables declaration//GEN-END:variables
}
