/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kelas;

/**
 *
 * @author User
 */
public class FormKelas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormKelas.class.getName());

    /**
     * Creates new form FormKelas
     */
    public FormKelas() {
        initComponents();
    loadData();
    tblKelas.getSelectionModel().addListSelectionListener(new javax.swing.event.ListSelectionListener() {
        public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
            isiFormDariTabel();
        }
    });  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textArea1 = new java.awt.TextArea();
        lblHeader = new java.awt.Label();
        lblIdKelas = new java.awt.Label();
        txtIdKelas = new java.awt.TextField();
        lblKodeMK = new java.awt.Label();
        txtKodeMK = new java.awt.TextField();
        lblIdDosen = new java.awt.Label();
        txtIdDosen = new java.awt.TextField();
        lblTahunAjaran = new java.awt.Label();
        txtTahunAjaran = new java.awt.TextField();
        lblSemester = new java.awt.Label();
        txtSemester = new java.awt.TextField();
        lblHari = new java.awt.Label();
        cbHari = new javax.swing.JComboBox<>();
        lblJamMulai = new java.awt.Label();
        txtJamMulai = new java.awt.TextField();
        lblJamSelesai = new java.awt.Label();
        txtJamSelesai = new java.awt.TextField();
        lblRuang = new java.awt.Label();
        txtRuang = new java.awt.TextField();
        btnTambah = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        Bersih = new javax.swing.JButton();
        jScrollPane1 = new java.awt.ScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKelas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHeader.setText("SISTEM KRS");

        lblIdKelas.setText("ID Kelas :");

        txtIdKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdKelasActionPerformed(evt);
            }
        });

        lblKodeMK.setText("Kode MK :");

        lblIdDosen.setText("ID Dosen :");

        lblTahunAjaran.setText("Thn Ajaran :");

        lblSemester.setText("Semester :");

        lblHari.setText("Hari :");

        cbHari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Senin", "Selasa", "Rabu", "Kamis", "Jumat" }));
        cbHari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHariActionPerformed(evt);
            }
        });

        lblJamMulai.setText("Jam Mulai :");

        txtJamMulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJamMulaiActionPerformed(evt);
            }
        });

        lblJamSelesai.setText("Jam Selesai :");

        lblRuang.setText("Ruang :");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapos");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        Bersih.setText("Bersih");
        Bersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BersihActionPerformed(evt);
            }
        });

        tblKelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblKelas);

        jScrollPane1.add(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblIdKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblKodeMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblIdDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(16, 16, 16)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtIdKelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtKodeMK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtIdDosen, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(lblTahunAjaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(lblSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(14, 14, 14)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(45, 45, 45)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblJamMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(14, 14, 14)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblJamSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblRuang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(31, 31, 31)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTahunAjaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSemester, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtJamMulai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbHari, javax.swing.GroupLayout.Alignment.TRAILING, 0, 88, Short.MAX_VALUE)
                                .addComponent(txtJamSelesai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtRuang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bersih)))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(336, Short.MAX_VALUE)
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(283, 283, 283))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblIdKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKodeMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKodeMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblIdDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTahunAjaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTahunAjaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblJamMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJamMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblJamSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJamSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRuang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRuang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTambah)
                            .addComponent(btnUpdate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHapus)
                            .addComponent(Bersih))
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdKelasActionPerformed
    txtIdKelas.setText("");
    txtIdKelas.setEditable(false);
    }//GEN-LAST:event_txtIdKelasActionPerformed

    private void cbHariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbHariActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
    java.sql.Connection c = null;
try {
    c = getConn();
    c.setAutoCommit(false);
    java.sql.PreparedStatement psK = c.prepareStatement(
        "INSERT INTO kelas (kode_mk, id_dosen, tahun_ajaran, semester) VALUES (?,?,?,?)",
        java.sql.Statement.RETURN_GENERATED_KEYS);
    psK.setString(1, txtKodeMK.getText());
    psK.setInt(2, Integer.parseInt(txtIdDosen.getText()));
    psK.setString(3, txtTahunAjaran.getText());
    psK.setString(4, txtSemester.getText());
    psK.executeUpdate();
    java.sql.ResultSet gk = psK.getGeneratedKeys();
    int idBaru = 0;
    if (gk.next()) idBaru = gk.getInt(1);
    java.sql.PreparedStatement psJ = c.prepareStatement(
        "INSERT INTO jadwal (id_kelas, hari, jam_mulai, jam_selesai, ruang) VALUES (?,?,?,?,?)");
    psJ.setInt(1, idBaru);
    psJ.setString(2, cbHari.getSelectedItem().toString());
    psJ.setString(3, txtJamMulai.getText());
    psJ.setString(4, txtJamSelesai.getText());
    psJ.setString(5, txtRuang.getText());
    psJ.executeUpdate();
    c.commit();
    javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");
    bersihForm();
    loadData();
    c.close();
} catch (java.sql.SQLException ex) {
    try { if (c != null) c.rollback(); } catch (java.sql.SQLException ignored) {}
    javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
    if (txtIdKelas.getText().isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "Pilih data di tabel dulu!");
    return;
}
java.sql.Connection c = null;
try {
    c = getConn();
    c.setAutoCommit(false);
    int idK = Integer.parseInt(txtIdKelas.getText());
    java.sql.PreparedStatement psK = c.prepareStatement(
        "UPDATE kelas SET kode_mk=?, id_dosen=?, tahun_ajaran=?, semester=? WHERE id_kelas=?");
    psK.setString(1, txtKodeMK.getText());
    psK.setInt(2, Integer.parseInt(txtIdDosen.getText()));
    psK.setString(3, txtTahunAjaran.getText());
    psK.setString(4, txtSemester.getText());
    psK.setInt(5, idK);
    psK.executeUpdate();
    java.sql.PreparedStatement psJ = c.prepareStatement(
        "UPDATE jadwal SET hari=?, jam_mulai=?, jam_selesai=?, ruang=? WHERE id_kelas=?");
    psJ.setString(1, cbHari.getSelectedItem().toString());
    psJ.setString(2, txtJamMulai.getText());
    psJ.setString(3, txtJamSelesai.getText());
    psJ.setString(4, txtRuang.getText());
    psJ.setInt(5, idK);
    psJ.executeUpdate();
    c.commit();
    javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil diupdate!");
    bersihForm();
    loadData();
    c.close();
} catch (java.sql.SQLException ex) {
    try { if (c != null) c.rollback(); } catch (java.sql.SQLException ignored) {}
    javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
    if (txtIdKelas.getText().isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "Pilih data di tabel dulu!");
    return;
}
int pilih = javax.swing.JOptionPane.showConfirmDialog(this, "Yakin hapus data ini?");
if (pilih == javax.swing.JOptionPane.YES_OPTION) {
    java.sql.Connection c = null;
    try {
        c = getConn();
        c.setAutoCommit(false);
        int idK = Integer.parseInt(txtIdKelas.getText());
        java.sql.PreparedStatement psJ = c.prepareStatement("DELETE FROM jadwal WHERE id_kelas=?");
        psJ.setInt(1, idK);
        psJ.executeUpdate();
        java.sql.PreparedStatement psK = c.prepareStatement("DELETE FROM kelas WHERE id_kelas=?");
        psK.setInt(1, idK);
        psK.executeUpdate();
        c.commit();
        javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
        bersihForm();
        loadData();
        c.close();
    } catch (java.sql.SQLException ex) {
        try { if (c != null) c.rollback(); } catch (java.sql.SQLException ignored) {}
        javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage());
    }
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void BersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BersihActionPerformed
    bersihForm();        // TODO add your handling code here:
    }//GEN-LAST:event_BersihActionPerformed

    private void txtJamMulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJamMulaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJamMulaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormKelas().setVisible(true));
    }
    private void loadData() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblKelas.getModel();
        model.setRowCount(0);
        model.setColumnIdentifiers(new String[]{"ID Kelas","Kode MK","ID Dosen","Thn Ajaran","Semester","Hari","Jam Mulai","Jam Selesai","Ruang"});
        String sql = "SELECT k.id_kelas, k.kode_mk, k.id_dosen, k.tahun_ajaran, k.semester, "
                   + "j.hari, j.jam_mulai, j.jam_selesai, j.ruang "
                   + "FROM kelas k LEFT JOIN jadwal j ON k.id_kelas = j.id_kelas";
        try {
            java.sql.Connection c = getConn();
            java.sql.Statement s = c.createStatement();
            java.sql.ResultSet r = s.executeQuery(sql);
            while (r.next()) {
                model.addRow(new Object[]{
                    r.getInt("id_kelas"),
                    r.getString("kode_mk"),
                    r.getInt("id_dosen"),
                    r.getString("tahun_ajaran"),
                    r.getString("semester"),
                    r.getString("hari"),
                    r.getString("jam_mulai"),
                    r.getString("jam_selesai"),
                    r.getString("ruang")
                });
            }
            c.close();
        } catch (java.sql.SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private java.sql.Connection getConn() throws java.sql.SQLException {
        return java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/krs", "root", "");
    }

    private void bersihForm() {
        txtIdKelas.setText("");
        txtKodeMK.setText("");
        txtIdDosen.setText("");
        txtTahunAjaran.setText("");
        txtSemester.setText("");
        cbHari.setSelectedIndex(0);
        txtJamMulai.setText("");
        txtJamSelesai.setText("");
        txtRuang.setText("");
        tblKelas.clearSelection();
    }

    private void isiFormDariTabel() {
        int row = tblKelas.getSelectedRow();
        if (row >= 0) {
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblKelas.getModel();
            txtIdKelas.setText(model.getValueAt(row, 0).toString());
            txtKodeMK.setText(model.getValueAt(row, 1).toString());
            txtIdDosen.setText(model.getValueAt(row, 2).toString());
            txtTahunAjaran.setText(model.getValueAt(row, 3).toString());
            txtSemester.setText(model.getValueAt(row, 4).toString());
            Object hari = model.getValueAt(row, 5);
            if (hari != null) cbHari.setSelectedItem(hari.toString());
            Object jm = model.getValueAt(row, 6);
            txtJamMulai.setText(jm != null ? jm.toString() : "");
            Object js = model.getValueAt(row, 7);
            txtJamSelesai.setText(js != null ? js.toString() : "");
            Object ruang = model.getValueAt(row, 8);
            txtRuang.setText(ruang != null ? ruang.toString() : "");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bersih;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbHari;
    private java.awt.ScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label lblHari;
    private java.awt.Label lblHeader;
    private java.awt.Label lblIdDosen;
    private java.awt.Label lblIdKelas;
    private java.awt.Label lblJamMulai;
    private java.awt.Label lblJamSelesai;
    private java.awt.Label lblKodeMK;
    private java.awt.Label lblRuang;
    private java.awt.Label lblSemester;
    private java.awt.Label lblTahunAjaran;
    private javax.swing.JTable tblKelas;
    private java.awt.TextArea textArea1;
    private java.awt.TextField txtIdDosen;
    private java.awt.TextField txtIdKelas;
    private java.awt.TextField txtJamMulai;
    private java.awt.TextField txtJamSelesai;
    private java.awt.TextField txtKodeMK;
    private java.awt.TextField txtRuang;
    private java.awt.TextField txtSemester;
    private java.awt.TextField txtTahunAjaran;
    // End of variables declaration//GEN-END:variables
}
