/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prodi;
import com.mycompany.mavenproject1.FormAdmin;
import com.mycompany.mavenproject1.database;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nicos
 */
public class FormProdi extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormProdi.class.getName());

    /**
     * Creates new form FormProdi
     */
    public FormProdi() {
        initComponents();
        jTable1.setDefaultEditor(Object.class, null);
        loadData();
    }
    
    private void loadData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Prodi");
        model.addColumn("Nama Prodi");

        database db = new database();
        try (Connection con = db.koneksi();
             Statement st = con.createStatement();
             ResultSet rs = st.executeQuery("SELECT * FROM prodi ORDER BY id_prodi")) {

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id_prodi"),
                    rs.getString("nama_prodi")
                });
    }

    } catch (SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Error: " + e.getMessage(), "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }

    jTable1.setModel(model);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Tambah = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Form Prodi");

        Tambah.setText("Tambah");
        Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahActionPerformed(evt);
            }
        });

        Edit.setText("Edit");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        Hapus.setText("Hapus");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Back)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Tambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Edit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Hapus))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tambah)
                    .addComponent(Edit)
                    .addComponent(Hapus))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        int baris = jTable1.getSelectedRow();
        if (baris == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Pilih prodi yang ingin diedit!",
                "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idProdi = (int) jTable1.getValueAt(baris, 0);
        String namaLama = (String) jTable1.getValueAt(baris, 1);

        String namaBaru = (String) javax.swing.JOptionPane.showInputDialog(this,
            "Edit nama prodi:", "Edit Prodi",
            javax.swing.JOptionPane.PLAIN_MESSAGE, null, null, namaLama);

        if (namaBaru == null || namaBaru.trim().isEmpty()) return;

        database db = new database();
        try (Connection con = db.koneksi();
             PreparedStatement ps = con.prepareStatement(
                 "UPDATE prodi SET nama_prodi=? WHERE id_prodi=?")) {

            ps.setString(1, namaBaru.trim());
            ps.setInt(2, idProdi);
            ps.executeUpdate();
            javax.swing.JOptionPane.showMessageDialog(this,
                "Prodi berhasil diupdate!", "Sukses",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
            loadData();

        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error: " + e.getMessage(), "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_EditActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        new FormAdmin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahActionPerformed
        String namaProdi = javax.swing.JOptionPane.showInputDialog(this,
        "Masukkan nama prodi baru:",
        "Tambah Prodi", javax.swing.JOptionPane.PLAIN_MESSAGE);

        if (namaProdi == null || namaProdi.trim().isEmpty()) return;

        database db = new database();
        try (Connection con = db.koneksi();
             PreparedStatement ps = con.prepareStatement(
                 "INSERT INTO prodi (nama_prodi) VALUES (?)")) {

            ps.setString(1, namaProdi.trim());
            ps.executeUpdate();
            javax.swing.JOptionPane.showMessageDialog(this,
                "Prodi berhasil ditambahkan!", "Sukses",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
            loadData();

        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error: " + e.getMessage(), "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_TambahActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        int baris = jTable1.getSelectedRow();
        if (baris == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Pilih prodi yang ingin dihapus!",
                "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this,
            "Yakin ingin menghapus prodi ini?",
            "Konfirmasi Hapus", javax.swing.JOptionPane.YES_NO_OPTION);

        if (konfirmasi != javax.swing.JOptionPane.YES_OPTION) return;

        int idProdi = (int) jTable1.getValueAt(baris, 0);

        database db = new database();
        try (Connection con = db.koneksi();
             PreparedStatement ps = con.prepareStatement(
                 "DELETE FROM prodi WHERE id_prodi=?")) {

            ps.setInt(1, idProdi);
            ps.executeUpdate();
            javax.swing.JOptionPane.showMessageDialog(this,
                "Prodi berhasil dihapus!", "Sukses",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
            loadData();

        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error: " + e.getMessage(), "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_HapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormProdi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Edit;
    private javax.swing.JButton Hapus;
    private javax.swing.JButton Tambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
